### ISSUE TITLE
Habitat Quality handle empty table fields

### ISSUE THREAD

**Issue by dcdenu4** [natcap/invest#1052]
A user posted an issue on the [forums](https://community.naturalcapitalproject.org/t/habitat-quality-valueerror-could-not-convert-string-to-float/2765) where they were getting the following error:

```python
2022-05-04 16:55:57,649 (natcap.invest.habitat_quality) habitat_quality.execute(259) INFO Starting execute of Habitat Quality model.
2022-05-04 16:55:57,649 (natcap.invest.habitat_quality) habitat_quality.execute(265) INFO Creating workspace
2022-05-04 16:55:57,688 (natcap.invest.habitat_quality) habitat_quality.execute(278) INFO Checking Threat and Sensitivity tables for compliance
2022-05-04 16:55:57,700 (natcap.invest.utils) utils.prepare_workspace(167) ERROR Exception while executing Habitat-Quality
Traceback (most recent call last):
  File "natcap\invest\utils.py", line 165, in prepare_workspace
  File "natcap\invest\ui\model.py", line 1649, in _logged_target
  File "natcap\invest\habitat_quality.py", line 293, in execute
  File "natcap\invest\habitat_quality.py", line 294, in <dictcomp>
ValueError: could not convert string to float: ''
2022-05-04 16:55:57,701 (natcap.invest.utils) utils.prepare_workspace(170) INFO Elapsed time: 0.06s
2022-05-04 16:55:57,701 (natcap.invest.utils) utils.prepare_workspace(173) INFO Execution finished
```

If this is just a case of the threat or sensitivity tables having an empty field, I feel like we could provide a better error message there.

Error reported using InVEST 3.10.2.

**Comment by dcdenu4** [comment]
Need to confirm this is still an issue.

**Comment by megannissel** [comment]
@dcdenu4 Fairly certain this is no longer an issue; I've run the model with permutations of the Threats Table and Sensitivity Table CSVs with empty strings in place of values, and the error reporting seems more robust in the current version of InVEST. E.g.:
```
ValueError: Value(s) in the "weight" column could not be interpreted as ratios. Original error: could not convert string to float: "''"
```

The one caveat I've found is in cases where a `NaN` value exists in the `MAX_DIST` column of the Threats Table. This doesn't get caught by validation (doesn't fly afoul of our `df[col] = df[col].astype(float)` check), and so the model eventually throws the following error:
```
    if row['max_dist'] <= 0:
       ^^^^^^^^^^^^^^^^^^^^
TypeError: '<=' not supported between instances of 'str' and 'int'
```
Notably, this level of detail is only available with the log level set to DEBUG (otherwise, you only see the TypeError and not the indicator that the problem is with `max_dist`). Thoughts on whether or not we should aim for more robust reporting in this case?

**Comment by dcdenu4** [comment]
Thanks @megannissel for looking into this! I think it would be nice to better validate against missing `max_dist` values in the CSV. I believe that we made a decision to allow for empty CSV entries, as sometimes they're optional. We don't as of yet have a way to specify if each row in a given column is required. Though we could. Either way, you're right that `numpy.nan` would be just fine as `astype(float)`.

So, I'd propose handling this in the `validate` function of `habitat_quality` as well as in the `execute` function. In the `execute` function, I think it's fine to add a `numpy.isnan()` check above the 0 threshold check and raise a `ValueError`.

Habitat Quality is a bit unique in how it handles it's CSVs and uses them for model runs.
