### ISSUE TITLE
Intermittent rec model test failure in GHA

### ISSUE THREAD

**Issue by davemfish** [natcap/invest#1170]
`tests/test_recreation.py::TestRecServer::test_empty_server`

I think this specific test times-out some percentage of the time. It would be nice to make it more reliable.

**Comment by davemfish** [comment]
Actually there is much more informative traceback from this test than just the timeout. I'm not sure why it times out, and I'm _really_ not sure how it ever passes, given this:

```
2023-02-07T16:18:33.3251990Z tests/test_recreation.py::TestRecServer::test_empty_server
2023-02-07T16:18:33.3253420Z   /Users/runner/micromamba-root/envs/env/lib/python3.8/site-packages/_pytest/threadexception.py:73: PytestUnhandledThreadExceptionWarning: Exception in thread Thread-1414
2023-02-07T16:18:33.3254520Z   
2023-02-07T16:18:33.3255240Z   Traceback (most recent call last):
2023-02-07T16:18:33.3256460Z     File "/Users/runner/micromamba-root/envs/env/lib/python3.8/threading.py", line 932, in _bootstrap_inner
2023-02-07T16:18:33.3257400Z       self.run()
2023-02-07T16:18:33.3258500Z     File "/Users/runner/micromamba-root/envs/env/lib/python3.8/threading.py", line 870, in run
2023-02-07T16:18:33.3260400Z       self._target(*self._args, **self._kwargs)
2023-02-07T16:18:33.3263430Z     File "/Users/runner/micromamba-root/envs/env/lib/python3.8/site-packages/natcap/invest/recreation/recmodel_server.py", line 815, in execute
2023-02-07T16:18:33.3264580Z       RecModel(args['raw_csv_point_data_path'], args['min_year'],
2023-02-07T16:18:33.3266470Z     File "/Users/runner/micromamba-root/envs/env/lib/python3.8/site-packages/natcap/invest/recreation/recmodel_server.py", line 92, in try_except_wrapper
2023-02-07T16:18:33.3267420Z       return func(*args, **kwargs)
2023-02-07T16:18:33.3269500Z     File "/Users/runner/micromamba-root/envs/env/lib/python3.8/site-packages/natcap/invest/recreation/recmodel_server.py", line 135, in __init__
2023-02-07T16:18:33.3271410Z       self.qt_pickle_filename = construct_userday_quadtree(
2023-02-07T16:18:33.3272880Z     File "/Users/runner/micromamba-root/envs/env/lib/python3.8/site-packages/natcap/invest/recreation/recmodel_server.py", line 638, in construct_userday_quadtree
2023-02-07T16:18:33.3274020Z       'only %.2fs', n_points * 100.0 / total_lines,
2023-02-07T16:18:33.3274850Z   ZeroDivisionError: float division by zero
```

As stated in the test, the main purpose of this test is to connect to a `RecModel` server with the `recmodel_client`. That is also done in at least one other test, using a non-empty CSV to initiate the server. So I think we can do without this test altogether.
