### ISSUE TITLE
Reclassification in Pollination doesn't provide contextual info about tables

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#1265]
This came up on the forums, where a reclassification for Pollination doesn't provide the extra tabular context that it could, which would make the exception more readable.  The exception stated was:

```
03/20/2023 11:27:34 pygeoprocessing.geoprocessing ERROR exception encountered in raster_calculator
Traceback (most recent call last):
File “pygeoprocessing\geoprocessing.py”, line 443, in raster_calculator
File “pygeoprocessing\geoprocessing.py”, line 1937, in _map_dataset_to_value_op
pygeoprocessing.geoprocessing.ReclassificationMissingValuesError: The following 10 raster values [11 22 23 31 41 42 52 71 90 95] from “D:\invest\tesis\cober.tif” do not have corresponding entries in the value map: {1: 1.0, 4: 0.6, 5: 0.6, 12: 0.9, 21: 0.4, 24: 0.3, 27: 0.2, 28: 0.4, 29: 1.0, 36: 0.6, 37: 0.6, 39: 0.9, 43: 0.4, 44: 0.3, 47: 0.2, 53: 0.4, 58: 1.0, 59: 0.6, 61: 0.6, 68: 0.9, 70: 0.4, 111: 0.3, 121: 0.2, 122: 0.4, 123: 1.0, 124: 0.6, 131: 0.6, 141: 0.9, 142: 0.4, 143: 0.3, 152: 0.2, 176: 0.4, 190: 0.4, 195: 0.3, 214: 0.2, 242: 0.4}.
```

Forums post: https://community.naturalcapitalproject.org/t/crop-pollination-something-went-wrong-when-adding-task-reclassify-to-substrate-cavity/3545

**Comment by dcdenu4** [comment]
After looking into this it seems like the `ValueError` with extra context is being provided, it just wasn't shown in the snapshot the user provided. What's happening is we are seeing both the error messages in the traceback and things can get a little jumbled with TaskGraph as well.

So there's maybe a broader question of, are these error handling wrappers actually helpful to users and should we use this model for future cases? Or, from a self help perspective, does this add to the confusion?

Going to remove the bug label and milestone for now.

```
08/10/2023 11:56:17  (pygeoprocessing.geoprocessing) geoprocessing.reproject_vector(1742) INFO starting reprojection
08/10/2023 11:56:17  (pygeoprocessing.geoprocessing) geoprocessing.reproject_vector(1784) INFO reprojection 100.0% complete on reprojected_farm_vector.shp
08/10/2023 11:56:17  (pygeoprocessing.geoprocessing) geoprocessing.raster_calculator(396) INFO starting stats_worker
08/10/2023 11:56:17  (pygeoprocessing.geoprocessing) geoprocessing.raster_calculator(402) INFO started stats_worker <Thread(Thread-1, started daemon 18796)>
08/10/2023 11:56:17  (pygeoprocessing.geoprocessing) geoprocessing.raster_calculator(498) ERROR exception encountered in raster_calculator
Traceback (most recent call last):
  File "C:\Users\ddenu\Workspace\NatCap\Repositories\venv-space\invest-debug\lib\site-packages\pygeoprocessing\geoprocessing.py", line 443, in raster_calculator
    target_block = local_op(*data_blocks)
  File "C:\Users\ddenu\Workspace\NatCap\Repositories\venv-space\invest-debug\lib\site-packages\pygeoprocessing\geoprocessing.py", line 1886, in _map_dataset_to_value_op
    raise ReclassificationMissingValuesError(
pygeoprocessing.geoprocessing.ReclassificationMissingValuesError: The following 4 raster values [90 91 92 93] from "C:\Users\ddenu\Downloads\pollination\landcover.tif" do not have corresponding entries in the value map: {1: 0.3, 2: 0.3, 3: 0.3, 4: 0.3, 6: 0.3, 7: 0.3, 8: 0.3, 11: 0.3, 16: 0.3, 18: 0.3, 20: 0.3, 21: 0.3, 24: 0.0, 29: 0.0, 32: 0.0, 33: 0.0, 39: 0.0, 49: 0.3, 51: 0.6, 52: 0.6, 53: 0.6, 54: 0.6, 55: 0.6, 56: 0.4, 57: 0.4, 58: 0.6, 59: 0.6, 60: 0.6, 61: 0.4, 62: 0.6, 66: 0.4, 67: 0.1, 68: 0.1, 71: 0.1, 72: 0.1, 73: 0.1, 74: 0.1, 75: 0.1, 76: 0.1, 78: 0.1, 79: 0.1, 80: 0.1, 81: 0.1, 82: 0.1, 83: 0.1, 84: 0.1, 85: 0.1, 86: 0.0, 87: 0.0, 88: 0.1, 89: 0.0}.
08/10/2023 11:56:17  (pygeoprocessing.geoprocessing) geoprocessing.raster_calculator(513) INFO Waiting for raster stats worker result.
08/10/2023 11:56:17  (taskgraph.Task) Task.add_task(706) ERROR Something went wrong when adding task reclassify_to_substrate_cavity (1), terminating taskgraph.
Traceback (most recent call last):
  File "C:\Users\ddenu\Workspace\NatCap\Repositories\venv-space\invest-debug\lib\site-packages\natcap\invest\utils.py", line 985, in reclassify_raster
    pygeoprocessing.reclassify_raster(
  File "C:\Users\ddenu\Workspace\NatCap\Repositories\venv-space\invest-debug\lib\site-packages\pygeoprocessing\geoprocessing.py", line 1893, in reclassify_raster
    raster_calculator(
  File "C:\Users\ddenu\Workspace\NatCap\Repositories\venv-space\invest-debug\lib\site-packages\pygeoprocessing\geoprocessing.py", line 443, in raster_calculator
    target_block = local_op(*data_blocks)
  File "C:\Users\ddenu\Workspace\NatCap\Repositories\venv-space\invest-debug\lib\site-packages\pygeoprocessing\geoprocessing.py", line 1886, in _map_dataset_to_value_op
    raise ReclassificationMissingValuesError(
pygeoprocessing.geoprocessing.ReclassificationMissingValuesError: The following 4 raster values [90 91 92 93] from "C:\Users\ddenu\Downloads\pollination\landcover.tif" do not have corresponding entries in the value map: {1: 0.3, 2: 0.3, 3: 0.3, 4: 0.3, 6: 0.3, 7: 0.3, 8: 0.3, 11: 0.3, 16: 0.3, 18: 0.3, 20: 0.3, 21: 0.3, 24: 0.0, 29: 0.0, 32: 0.0, 33: 0.0, 39: 0.0, 49: 0.3, 51: 0.6, 52: 0.6, 53: 0.6, 54: 0.6, 55: 0.6, 56: 0.4, 57: 0.4, 58: 0.6, 59: 0.6, 60: 0.6, 61: 0.4, 62: 0.6, 66: 0.4, 67: 0.1, 68: 0.1, 71: 0.1, 72: 0.1, 73: 0.1, 74: 0.1, 75: 0.1, 76: 0.1, 78: 0.1, 79: 0.1, 80: 0.1, 81: 0.1, 82: 0.1, 83: 0.1, 84: 0.1, 85: 0.1, 86: 0.0, 87: 0.0, 88: 0.1, 89: 0.0}.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ddenu\Workspace\NatCap\Repositories\venv-space\invest-debug\lib\site-packages\taskgraph\Task.py", line 674, in add_task
    new_task._call()
  File "C:\Users\ddenu\Workspace\NatCap\Repositories\venv-space\invest-debug\lib\site-packages\taskgraph\Task.py", line 1093, in _call
    payload = self._func(*self._args, **self._kwargs)
  File "C:\Users\ddenu\Workspace\NatCap\Repositories\venv-space\invest-debug\lib\site-packages\natcap\invest\utils.py", line 995, in reclassify_raster
    raise ValueError(error_message)
ValueError: Values in the LULC raster were found that are not represented under the 'lucode' column of the Biophysical table. The missing values found in the LULC raster but not the table are: [90 91 92 93].
Traceback (most recent call last):
  File "C:\Users\ddenu\Workspace\NatCap\Repositories\venv-space\invest-debug\lib\site-packages\natcap\invest\utils.py", line 985, in reclassify_raster
    pygeoprocessing.reclassify_raster(
  File "C:\Users\ddenu\Workspace\NatCap\Repositories\venv-space\invest-debug\lib\site-packages\pygeoprocessing\geoprocessing.py", line 1893, in reclassify_raster
    raster_calculator(
  File "C:\Users\ddenu\Workspace\NatCap\Repositories\venv-space\invest-debug\lib\site-packages\pygeoprocessing\geoprocessing.py", line 443, in raster_calculator
    target_block = local_op(*data_blocks)
  File "C:\Users\ddenu\Workspace\NatCap\Repositories\venv-space\invest-debug\lib\site-packages\pygeoprocessing\geoprocessing.py", line 1886, in _map_dataset_to_value_op
    raise ReclassificationMissingValuesError(
pygeoprocessing.geoprocessing.ReclassificationMissingValuesError: The following 4 raster values [90 91 92 93] from "C:\Users\ddenu\Downloads\pollination\landcover.tif" do not have corresponding entries in the value map: {1: 0.3, 2: 0.3, 3: 0.3, 4: 0.3, 6: 0.3, 7: 0.3, 8: 0.3, 11: 0.3, 16: 0.3, 18: 0.3, 20: 0.3, 21: 0.3, 24: 0.0, 29: 0.0, 32: 0.0, 33: 0.0, 39: 0.0, 49: 0.3, 51: 0.6, 52: 0.6, 53: 0.6, 54: 0.6, 55: 0.6, 56: 0.4, 57: 0.4, 58: 0.6, 59: 0.6, 60: 0.6, 61: 0.4, 62: 0.6, 66: 0.4, 67: 0.1, 68: 0.1, 71: 0.1, 72: 0.1, 73: 0.1, 74: 0.1, 75: 0.1, 76: 0.1, 78: 0.1, 79: 0.1, 80: 0.1, 81: 0.1, 82: 0.1, 83: 0.1, 84: 0.1, 85: 0.1, 86: 0.0, 87: 0.0, 88: 0.1, 89: 0.0}.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ddenu\Downloads\pollination\execute_invest_pollination.py", line 33, in <module>
    natcap.invest.pollination.execute(args)
  File "C:\Users\ddenu\Workspace\NatCap\Repositories\venv-space\invest-debug\lib\site-packages\natcap\invest\pollination.py", line 561, in execute
    landcover_substrate_index_tasks[substrate] = task_graph.add_task(
  File "C:\Users\ddenu\Workspace\NatCap\Repositories\venv-space\invest-debug\lib\site-packages\taskgraph\Task.py", line 674, in add_task
    new_task._call()
  File "C:\Users\ddenu\Workspace\NatCap\Repositories\venv-space\invest-debug\lib\site-packages\taskgraph\Task.py", line 1093, in _call
    payload = self._func(*self._args, **self._kwargs)
  File "C:\Users\ddenu\Workspace\NatCap\Repositories\venv-space\invest-debug\lib\site-packages\natcap\invest\utils.py", line 995, in reclassify_raster
    raise ValueError(error_message)
ValueError: Values in the LULC raster were found that are not represented under the 'lucode' column of the Biophysical table. The missing values found in the LULC raster but not the table are: [90 91 92 93].
```
