### ISSUE TITLE
Rec server crashes when out of memory

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#1284]
Every once in a while, the recreation server crashes.  Yesterday's crash was related to `python` eating up too much memory and `oom-killer` terminating the process (see the [syslog for it here, stanford auth required](https://drive.google.com/file/d/1W-nZPgZVGXG-V44zb3nb8YW6YumHT6y0/view?usp=share_link)).

This kind of error happens when we're requested more active memory than is available and it cannot be served by virtual memory.  More than likely, someone requested an analysis area that is too large.  It'd be nice if we could handle this case and refuse to serve requests that will be too large.

Given that a recmodel-v2 is planned, I'm not sure that this is worth any effort at this point, but if we were to keep this around for a while longer, it might be nice to automate a restart of the recserver process (maybe a heartbeat monitor cron job?) or even a notification when the server goes down so we aren't 100% relying on the forums.

**Comment by davemfish** [comment]
Here's a recent example from the server's log. Note the unreasonably large bounding box. We should deny this request outright, I think.

```
11/22/2023 18:18:12  natcap.invest.recreation.recmodel_server INFO     running calc user days on ./recserver_cache_py36/50415363-ff30-445d-81c8-43738aa603c5
11/22/2023 18:18:12  natcap.invest.recreation.recmodel_server INFO     querying global quadtree against [-179.14199829101562, -55.91972351074219, 179.7774658203125, 83.62359619140625]
11/22/2023 18:52:39  natcap.invest.recreation.recmodel_server ERROR    exception in calc_photo_user_days_in_aoi
Unable to allocate 1.32 GiB for an array with shape (70717586,) and data type [('f0', '<M8[D]'), ('f1', 'S4'), ('f2', '<f4'), ('f3', '<f4')]
Traceback (most recent call last):
  File "/usr/local/recreation-server/invest/env/lib/python3.7/site-packages/natcap.invest-3.8.8.post374+gd1cac43-py3.7-linux-x86_64.egg/natcap/invest/recreation/recmodel_server.py", line 66, in try_except_wrapper
    return func(*args, **kwargs)
  File "/usr/local/recreation-server/invest/env/lib/python3.7/site-packages/natcap.invest-3.8.8.post374+gd1cac43-py3.7-linux-x86_64.egg/natcap/invest/recreation/recmodel_server.py", line 200, in calc_photo_user_days_in_aoi
    out_vector_filename))
  File "/usr/local/recreation-server/invest/env/lib/python3.7/site-packages/natcap.invest-3.8.8.post374+gd1cac43-py3.7-linux-x86_64.egg/natcap/invest/recreation/recmodel_server.py", line 297, in _calc_aggregated_points_in_aoi
    global_b_box)
  File "src/natcap/invest/recreation/out_of_core_quadtree.pyx", line 345, in natcap.invest.recreation.out_of_core_quadtree.OutOfCoreQuadTree.get_intersecting_points_in_bounding_box
  File "src/natcap/invest/recreation/out_of_core_quadtree.pyx", line 345, in natcap.invest.recreation.out_of_core_quadtree.OutOfCoreQuadTree.get_intersecting_points_in_bounding_box
  File "src/natcap/invest/recreation/out_of_core_quadtree.pyx", line 344, in natcap.invest.recreation.out_of_core_quadtree.OutOfCoreQuadTree.get_intersecting_points_in_bounding_box
  File "<__array_function__ internals>", line 6, in concatenate
MemoryError: Unable to allocate 1.32 GiB for an array with shape (70717586,) and data type [('f0', '<M8[D]'), ('f1', 'S4'), ('f2', '<f4'), ('f3', '<f4')]
```

**Comment by davemfish** [comment]
This will be resolved in #1551 where the server has a manager process that will not crash even when one of the subprocesses doing the calculations does crash.

**Comment by davemfish** [comment]
Done in #1832
