### ISSUE TITLE
Binary build failures on GHA macos-latest

### ISSUE THREAD

**Issue by davemfish** [natcap/invest#1339]
It seems like this must have been triggered by an OS update? There was an macOS upgrade for the runners a few days ago. https://github.com/actions/runner-images/releases

This doesn't seem like our bug, but I haven't found mention of it anywhere else yet. The exception is from,
```
2023-06-23T18:07:31.5238040Z subprocess.CalledProcessError: Command '['/Users/runner/work/invest/invest/dist/invest/invest', '-sS', '-c', 'import platform; print(platform.mac_ver()[0])']' returned non-zero exit status 2.
```

https://github.com/natcap/invest/actions/runs/5358675028/jobs/9722366040
```
2023-06-23T18:06:36.8749610Z dist/invest/invest list
2023-06-23T18:07:30.8626000Z usage: invest [-h] [--version] [-v | --debug]
2023-06-23T18:07:30.8730470Z               [--taskgraph-log-level {DEBUG,INFO,WARNING,ERROR}]
2023-06-23T18:07:30.8769960Z               [-L {en,es,zh}]
2023-06-23T18:07:30.8809550Z               {list,run,validate,getspec,serve,export-py} ...
2023-06-23T18:07:30.8869260Z invest: error: argument subcommand: invalid choice: 'import platform; print(platform.mac_ver()[0])' (choose from 'list', 'run', 'validate', 'getspec', 'serve', 'export-py')
2023-06-23T18:07:31.4447430Z Traceback (most recent call last):
2023-06-23T18:07:31.4565640Z   File "invest/cli.py", line 16, in <module>
2023-06-23T18:07:31.4667460Z   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2023-06-23T18:07:31.4754900Z   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
2023-06-23T18:07:31.4856940Z   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
2023-06-23T18:07:31.4958690Z   File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
2023-06-23T18:07:31.4970270Z   File "natcap/invest/datastack.py", line 37, in <module>
2023-06-23T18:07:31.5071900Z   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2023-06-23T18:07:31.5173800Z   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
2023-06-23T18:07:31.5187710Z   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
2023-06-23T18:07:31.5193580Z   File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
2023-06-23T18:07:31.5194280Z   File "natcap/invest/utils.py", line 15, in <module>
2023-06-23T18:07:31.5194700Z   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2023-06-23T18:07:31.5195100Z   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
2023-06-23T18:07:31.5195690Z   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
2023-06-23T18:07:31.5196160Z   File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
2023-06-23T18:07:31.5196620Z   File "pygeoprocessing/__init__.py", line 11, in <module>
2023-06-23T18:07:31.5197060Z   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2023-06-23T18:07:31.5197500Z   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
2023-06-23T18:07:31.5197880Z   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
2023-06-23T18:07:31.5198570Z   File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
2023-06-23T18:07:31.5199070Z   File "pygeoprocessing/geoprocessing.py", line 19, in <module>
2023-06-23T18:07:31.5199470Z   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2023-06-23T18:07:31.5199860Z   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
2023-06-23T18:07:31.5200740Z   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
2023-06-23T18:07:31.5201130Z   File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
2023-06-23T18:07:31.5201510Z   File "scipy/interpolate/__init__.py", line 167, in <module>
2023-06-23T18:07:31.5201880Z   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2023-06-23T18:07:31.5202270Z   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
2023-06-23T18:07:31.5202640Z   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
2023-06-23T18:07:31.5214710Z   File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
2023-06-23T18:07:31.5215400Z   File "scipy/interpolate/_interpolate.py", line 12, in <module>
2023-06-23T18:07:31.5215990Z   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2023-06-23T18:07:31.5216560Z   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
2023-06-23T18:07:31.5217030Z   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
2023-06-23T18:07:31.5217610Z   File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
2023-06-23T18:07:31.5218030Z   File "scipy/interpolate/_fitpack_py.py", line 10, in <module>
2023-06-23T18:07:31.5218400Z   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2023-06-23T18:07:31.5218790Z   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
2023-06-23T18:07:31.5219170Z   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
2023-06-23T18:07:31.5219560Z   File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
2023-06-23T18:07:31.5219940Z   File "scipy/interpolate/_bsplines.py", line 8, in <module>
2023-06-23T18:07:31.5220300Z   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2023-06-23T18:07:31.5220690Z   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
2023-06-23T18:07:31.5221070Z   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
2023-06-23T18:07:31.5222290Z   File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
2023-06-23T18:07:31.5222760Z   File "scipy/optimize/__init__.py", line 405, in <module>
2023-06-23T18:07:31.5223130Z   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2023-06-23T18:07:31.5223510Z   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
2023-06-23T18:07:31.5224030Z   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
2023-06-23T18:07:31.5224480Z   File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
2023-06-23T18:07:31.5225450Z   File "scipy/optimize/_minimize.py", line 26, in <module>
2023-06-23T18:07:31.5225880Z   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2023-06-23T18:07:31.5226290Z   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
2023-06-23T18:07:31.5226660Z   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
2023-06-23T18:07:31.5227050Z   File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
2023-06-23T18:07:31.5227440Z   File "scipy/optimize/_trustregion_constr/__init__.py", line 4, in <module>
2023-06-23T18:07:31.5227820Z   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2023-06-23T18:07:31.5228210Z   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
2023-06-23T18:07:31.5228580Z   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
2023-06-23T18:07:31.5228950Z   File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
2023-06-23T18:07:31.5229380Z   File "scipy/optimize/_trustregion_constr/minimize_trustregion_constr.py", line 5, in <module>
2023-06-23T18:07:31.5229790Z   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2023-06-23T18:07:31.5230170Z   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
2023-06-23T18:07:31.5230740Z   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
2023-06-23T18:07:31.5231490Z   File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
2023-06-23T18:07:31.5231860Z   File "scipy/optimize/_constraints.py", line 8, in <module>
2023-06-23T18:07:31.5232230Z   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2023-06-23T18:07:31.5232620Z   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
2023-06-23T18:07:31.5233010Z   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
2023-06-23T18:07:31.5233390Z   File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
2023-06-23T18:07:31.5233830Z   File "numpy/testing/__init__.py", line 11, in <module>
2023-06-23T18:07:31.5234190Z   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2023-06-23T18:07:31.5234580Z   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
2023-06-23T18:07:31.5234950Z   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
2023-06-23T18:07:31.5235340Z   File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
2023-06-23T18:07:31.5235710Z   File "numpy/testing/_private/utils.py", line 64, in <module>
2023-06-23T18:07:31.5236140Z   File "packaging/tags.py", line 536, in sys_tags
2023-06-23T18:07:31.5236500Z   File "packaging/tags.py", line 211, in cpython_tags
2023-06-23T18:07:31.5236840Z   File "packaging/tags.py", line 399, in mac_platforms
2023-06-23T18:07:31.5237160Z   File "subprocess.py", line 526, in run
2023-06-23T18:07:31.5238040Z subprocess.CalledProcessError: Command '['/Users/runner/work/invest/invest/dist/invest/invest', '-sS', '-c', 'import platform; print(platform.mac_ver()[0])']' returned non-zero exit status 2.
2023-06-23T18:07:31.5238660Z [18368] Failed to execute script 'cli' due to unhandled exception!
2023-06-23T18:07:31.5965980Z make: *** [dist/invest] Error 1
```

**Comment by davemfish** [comment]
Judging by recent builds, this has resolved itself. Not our bug.
