### ISSUE TITLE
Urban Nature Access crashes with cryptic type error

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#1350]
A [user on the forums](https://community.naturalcapitalproject.org/t/urban-nature-access-model-typeerror-wrong-number-or-type-of-arguments-for-overloaded-function-feature-setfield/3842) reported an interesting GDAL-land `TypeError`:

```
2023-06-22 12:16:47,682 (taskgraph.Task) Task.add_task(706) ERROR Something went wrong when adding task Aggregate supply-demand to admin units (single rasters) (16), terminating taskgraph.
Traceback (most recent call last):
  File "taskgraph\Task.py", line 674, in add_task
  File "taskgraph\Task.py", line 1093, in _call
  File "natcap\invest\urban_nature_access.py", line 1981, in _supply_demand_vector_for_single_raster_modes
  File "natcap\invest\urban_nature_access.py", line 2018, in _write_supply_demand_vector
  File "osgeo\ogr.py", line 4392, in SetField
TypeError: Wrong number or type of arguments for overloaded function 'Feature_SetField'.
  Possible C/C++ prototypes are:
    OGRFeatureShadow::SetField(int,char const *)
    OGRFeatureShadow::SetField(char const *,char const *)
    OGRFeatureShadow::SetField(int,double)
    OGRFeatureShadow::SetField(char const *,double)
    OGRFeatureShadow::SetField(int,int,int,int,int,int,float,int)
    OGRFeatureShadow::SetField(char const *,int,int,int,int,int,float,int)
```

This is curious because I sent him a dev build and the numerical values look fine.  I've requested his data to dig into it.

**Comment by phargogh** [comment]
I confirmed with the user that casting the value to a `float` before setting the value in the field resolved the issue.
