### ISSUE TITLE
Unhandled gdal error silently failing HQ model

### ISSUE THREAD

**Issue by dcdenu4** [natcap/invest#1484]
A user [posted](https://community.naturalcapitalproject.org/t/habitat-quality-invest-3-10-2-vs-3-14-0/4354) about experiencing an error with HQ in 3.14.0. The logfiles revelead:

```python
2023-11-30 19:02:22,959 (natcap.invest.habitat_quality) habitat_quality.execute(471) INFO Aligning, resizing, and reprojecting raster inputs to that of the current land cover.
2023-11-30 19:02:23,146 (pygeoprocessing.geoprocessing) geoprocessing.align_and_resize_raster_stack(996) INFO 1 of 5 aligned: LULC_reclass_habitat_pic_aligned_pic_New.tif
2023-11-30 19:02:23,214 (pygeoprocessing.geoprocessing) geoprocessing.align_and_resize_raster_stack(996) INFO 2 of 5 aligned: AGRI_aligned_pic_New.tif
2023-11-30 19:02:23,218 (osgeo) utils._log_gdal_errors(97) ERROR [errno 6] Cannot find coordinate operations from `ENGCRS["NAD83 / Quebec Lambert",EDATUM[""],CS[Cartesian,2],AXIS["(E)",east,ORDER[1],LENGTHUNIT["metre",1,ID["EPSG",9001]]],AXIS["(N)",north,ORDER[2],LENGTHUNIT["metre",1,ID["EPSG",9001]]]]' to `EPSG:32198'
2023-11-30 19:02:23,218 (pygeoprocessing.geoprocessing) geoprocessing.align_and_resize_raster_stack(996) INFO 3 of 5 aligned: ROAD_aligned_pic_New.tif
2023-11-30 19:02:23,275 (pygeoprocessing.geoprocessing) geoprocessing.align_and_resize_raster_stack(996) INFO 4 of 5 aligned: BUILT_aligned_pic_New.tif
2023-11-30 19:02:23,334 (pygeoprocessing.geoprocessing) geoprocessing.align_and_resize_raster_stack(996) INFO 5 of 5 aligned: EDGE_aligned_pic_New.tif
2023-11-30 19:02:23,335 (pygeoprocessing.geoprocessing) geoprocessing.align_and_resize_raster_stack(1000) INFO aligned all 5 rasters.
2023-11-30 19:02:23,337 (taskgraph.Task) Task.add_task(706) ERROR Something went wrong when adding task align_input_rasters (4), terminating taskgraph.
Traceback (most recent call last):
  File "taskgraph/Task.py", line 674, in add_task
  File "taskgraph/Task.py", line 1109, in _call
RuntimeError: In Task: align_input_rasters (4)
Missing expected target path results.
```

I'm not sure I've ever seen this before, but it looks like the aligned step succeeded when in fact, I don't think that aligned output ever gets created. It would be great to better handle an error message like this.

**Comment by dcdenu4** [comment]
Similar issue popping up in NDR with the same user: https://community.naturalcapitalproject.org/t/ndr-output-version-3-10-2-vs-3-14-0/4351/2

**Comment by emlys** [comment]
I think this situation would be handled better if we enable `gdal.UseExceptions()`. Then the GDAL error would be raised as a python error and stop execution where the issue happens. Rather than just logging the error message and continuing until another problem results from it downstream.

**Comment by dcdenu4** [comment]
Related, [pygeoprocessing](https://github.com/natcap/pygeoprocessing/pull/402) will in the future use `gdal.UseExceptions()` and our plan is to have InVEST as well.

So, this error handling could shake as resolved from including `gdal.UseExceptions()` in the near future.

**Comment by davemfish** [comment]
On hold in favor of doing https://github.com/natcap/invest/issues/1570
