### ISSUE TITLE
UNA: `NameError` name 'expected_distance' is not defined

### ISSUE THREAD

**Issue by davemfish** [natcap/invest#1579]
Yingjie reports: 

> I run the model with the same setting and the model reported the same error. I attached her log file for your reference.
* search_radius_mode:           uniform radius
* decay_function:  exponential

```
2024-05-19 10:55:29,083 (natcap.invest.utils) utils.prepare_workspace(161) Level 100 Writing log messages to [E:\invest\urban nature access\demo3\InVEST-natcap.invest.urban_nature_access-log-2024-05-19--10_55_29.txt]
2024-05-19 10:55:29,083 (__main__) cli.main(459) Level 100 Starting model with parameters: 
Arguments for InVEST natcap.invest.urban_nature_access 3.14.1:
admin_boundaries_vector_path E:\invest\urban nature access\data\UrbanNatureAccess\administrative-units.shp
aggregate_by_pop_group       True
decay_function               exponential
lulc_attribute_table         E:\invest\urban nature access\data\UrbanNatureAccess\lulc-attributes.csv
lulc_raster_path             E:\invest\urban nature access\data\UrbanNatureAccess\paris-lulc.tif
n_workers                    -1
population_group_radii_table E:\invest\urban nature access\data\UrbanNatureAccess\pop-group-radii.csv
population_raster_path       E:\invest\urban nature access\data\UrbanNatureAccess\population.tif
results_suffix               
search_radius                200
search_radius_mode           uniform radius
urban_nature_demand          11
workspace_dir                E:\invest\urban nature access\demo3

2024-05-19 10:55:29,083 (natcap.invest.urban_nature_access) urban_nature_access.execute(697) INFO Starting Urban Nature Access Model
2024-05-19 10:55:29,087 (natcap.invest.urban_nature_access) urban_nature_access.execute(732) INFO Using decay function exponential
2024-05-19 10:55:29,868 (natcap.invest.utils) utils.prepare_workspace(166) ERROR Exception while executing natcap.invest.urban_nature_access
Traceback (most recent call last):
  File "natcap\invest\utils.py", line 164, in prepare_workspace
  File "invest\cli.py", line 470, in main
  File "natcap\invest\urban_nature_access.py", line 977, in execute
NameError: name 'expected_distance' is not defined
2024-05-19 10:55:29,869 (natcap.invest.utils) utils.prepare_workspace(169) INFO Elapsed time: 0.79s
2024-05-19 10:55:29,869 (natcap.invest.utils) utils.prepare_workspace(172) INFO Execution finished
```

**Comment by davemfish** [comment]
@phargogh turns out this `NameError` does not exist on `main`. I tested the model with the parameters that used to trigger it. All good.

**Comment by davemfish** [comment]
This was a duplicate all along. https://github.com/natcap/invest/issues/1502
