### ISSUE TITLE
Workbench crashes when anaconda is on the PATH

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#1643]
A student in the InVEST class was unable to launch the InVEST workbench on Windows, and the workbench logfile looked like this:

```python
[17:57:52.975] [C:\Program Files\InVEST 3.14.2 Workbench\resources\app.asar\build\main\main.js] Windows detected, requesting single instance lock
[17:57:53.030] [C:\Program Files\InVEST 3.14.2 Workbench\resources\app.asar\build\main\main.js] Running invest-workbench version 3.14.2
[17:57:56.008] [C:\Program Files\InVEST 3.14.2 Workbench\resources\app.asar\build\main\main.js] Found invest binaries "C:\Program Files\InVEST 3.14.2 Workbench\resources\invest\invest.exe" for version 
[17:57:56.017] [C:\Program Files\InVEST 3.14.2 Workbench\resources\app.asar\build\main\main.js] Started python process as PID 13576
[17:57:56.338] [C:\Program Files\InVEST 3.14.2 Workbench\resources\app.asar\build\main\main.js] retry # 1
[17:57:56.398] [C:\Program Files\InVEST 3.14.2 Workbench\resources\app.asar\build\main\main.js] Traceback (most recent call last):
  File "osgeo\__init__.py", line 30, in swig_import_helper

[17:57:56.399] [C:\Program Files\InVEST 3.14.2 Workbench\resources\app.asar\build\main\main.js]   File "importlib\__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 921, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 813, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1289, in create_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
ImportError: DLL load failed while importing _gdal: The specified procedure could not be found.

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "invest\cli.py", line 16, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "natcap\invest\datastack.py", line 35, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "osgeo\__init__.py", line 35, in <module>
  File "osgeo\__init__.py", line 32, in swig_import_helper
  File "importlib\__init__.py", line 90, in import_module
ModuleNotFoundError: No module named '_gdal'
[1380] Failed to execute script 'cl
[17:57:56.399] [C:\Program Files\InVEST 3.14.2 Workbench\resources\app.asar\build\main\main.js] i' due to unhandled exception!
```

The specific PATH entries that were preventing InVEST from launching were:
* `C:\Program Files\Anaconda\Scripts`
* `C:\Program Files\Anaconda\Library\bin`
* `C:\Program Files\Anaconda\condabin`

When the student removed all three of these entries (I do not know if they tested each one individually), the workbench was able to launch.

A few other observations about the student's system:
* Windows 11
* The user's username had all ascii characters and no spaces, e.g. `C:\Users\phargogh\`
* There were no gdal-related environment variables defined
* There _was_ a `PYTHONPATH` environment variable defined, but it appeared to refer to a chemistry workspace, and so was unlikely to have affected this situation.
* 

The student had a username that was entirely ASCII character

**Comment by phargogh** [comment]
#1610 is related since it'd be helpful to inspect the cause of the error without having to dig into the logs directory.

**Comment by davemfish** [comment]
I'll see if I can reproduce this

**Comment by davemfish** [comment]
I was able to reproduce this after installing GDAL in the anaconda base environment. The `osgeo` import is searching all the entries in `PATH` for any directory containing a `gdal*.dll`. If it doesn't find one, the invest binaries are able to import gdal just fine. But in the case above, it _is_ finding incompatible dlls from anaconda before/instead of finding the ones from the pyinstaller binaries.

See https://github.com/OSGeo/gdal/blob/v3.9.0/swig/python/osgeo/__init__.py

It's also not clear to me why the directory containing `gdal.dll` from pyinstaller is _not_ on the PATH. Pyinstaller seems to add this to the PATH:

`C:\Users\dmf\projects\invest\dist\invest\_internal\pywin32_system32`

But `gdal.dll` is actually in `C:\Users\dmf\projects\invest\dist\invest\_internal`.
