### ISSUE TITLE
Uncaught error when loading an invalid datastack file

### ISSUE THREAD

**Issue by dcdenu4** [natcap/invest#1668]
I accidentally dragged and dropped into an InVEST model form instead of input field. The Workbench froze for a bit but recovered. The error I see is:

```python
[1] [14:50:59.609] [undefined] 10/28/2024 14:50:59  werkzeug           INFO     127.0.0.1 - - [28/Oct/2024 14:50:59] "OPTIONS /api/post_datastack_file HTTP/1.1" 200 -
[1]
[1] [14:51:07.198] [undefined] 10/28/2024 14:51:07  natcap.invest.ui_server ERROR    Exception on /api/post_datastack_file [POST]
[1] Traceback (most recent call last):
[1]   File "C:\Users\ddenu\Workspace\Repositories\venvs\schisto\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
[1]     response = self.full_dispatch_request()
[1]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1]   File "C:\Users\ddenu\Workspace\Repositories\venvs\schisto\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
[1]     rv = self.handle_user_exception(e)
[1]          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1]   File "C:\Users\ddenu\Workspace\Repositories\venvs\schisto\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
[1]     return cors_after_request(app.make_response(f(*args, **kwargs)))
[1]                                                 ^^^^^^^^^^^^^^^^^^
[1]   File "C:\Users\ddenu\Workspace\Repositories\venvs\schisto\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
[1]     rv = self.dispatch_request()
[1]          ^^^^^^^^^^^^^^^^^^^^^^^
[1]   File "C:\Users\ddenu\Workspace\Repositories\venvs\schisto\Lib\site-packages\flask\app.py", line 865, in dispatch_request
[1]     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
[1]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1]   File "C:\Users\ddenu\Workspace\Repositories\venvs\schisto\Lib\site-packages\natcap\invest\ui_server.py", line 166, in post_datastack_file
[1]     stack_type, stack_info = datastack.get_datastack_info(
[1]                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1]   File "C:\Users\ddenu\Workspace\Repositories\venvs\schisto\Lib\site-packages\natcap\invest\datastack.py", line 214, in get_datastack_info
[1]     return 'logfile', extract_parameters_from_logfile(filepath)
[1]                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1]   File "C:\Users\ddenu\Workspace\Repositories\venvs\schisto\Lib\site-packages\natcap\invest\datastack.py", line 673, in extract_parameters_from_logfile
[1]     for line in logfile:
[1]   File "<frozen codecs>", line 720, in __next__
[1]   File "<frozen codecs>", line 648, in __next__
[1]   File "<frozen codecs>", line 561, in readline
[1]   File "<frozen codecs>", line 507, in read
[1] UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 36: invalid start byte
[1]
[1] [14:51:07.203] [undefined] Error: Unexpected token '<', "<!doctype "... is not valid JSON
```

**Comment by davemfish** [comment]
@dcdenu4 what would you say is the bug here? The way the Workbench reacted?
