### ISSUE TITLE
HQ: Improve error message when sensitivity table has a missing value

### ISSUE THREAD

**Issue by davemfish** [natcap/invest#1671]
Habitat Quality fails with a cryptic error if the table used for a raster reclass has a missing value in the `lulc` column, in a row that contains other data:

```python
Traceback (most recent call last):
  File "natcap\invest\utils.py", line 165, in prepare_workspace
  File "invest\cli.py", line 470, in main
  File "natcap\invest\habitat_quality.py", line 587, in execute
  File "taskgraph\Task.py", line 674, in add_task
  File "taskgraph\Task.py", line 1093, in _call
  File "natcap\invest\utils.py", line 732, in reclassify_raster
  File "pygeoprocessing\geoprocessing.py", line 2374, in reclassify_raster
  File "numpy\core\numeric.py", line 2348, in isclose
TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

Example table:
![Capture](https://github.com/user-attachments/assets/1d9d3fba-c318-4510-b30a-1af591451590)

It would be nice to improve the error-handling here so that it's clear what the problem is. This might boil down to checking for `None` in the keys of the `value_map` passed to `reclassify_raster`. 

There are probably a number of places in invest where it might make sense to do this, but in order to make a helpful message, we may need to handle each case individually.

**Comment by davemfish** [comment]
The missing value actually ends up as a `pandas.NA` value, not a `None` value, after reading in the CSV with `validation.get_validated_dataframe`. Both raise the same `TypeError` if passed to `numpy.isclose`.

**Comment by davemfish** [comment]
@claire-simpson I just tried loading the CSV with `utils.read_csv_to_dataframe` and it loads the missing value as `numpy.nan`. So probably makes sense to guard against that one as well, like you were saying.
