### ISSUE TITLE
Plugins: renderer crashed after removing plugin

### ISSUE THREAD

**Issue by davemfish** [natcap/invest#1692]
I admit I intentionally left the plugin model's tab open while I removed the plugin. From the logs, it looks like plugin removal was successful, but then the react tree crashed. There were also a couple files that could not be removed. I'm not sure if that's also related to the tab being open.

```javascript
[09:32:54.213] [undefined] removing plugin schistosomiasis
[09:32:54.215] [undefined] "C:/Users/dmf/AppData/Local/Programs/InVEST 3.14.2.post414+g69776618d Workbench/resources/miniforge3/condabin/mamba.bat" [
  'remove',
  '--yes',
  '--prefix',
  '"C:\\Users\\dmf\\AppData\\Local\\Programs\\InVEST 3.14.2.post387+g366216a2f Workbench\\resources\\Miniforge3\\envs\\invest_plugin_schistosomiasis"',
  '--all'
]
[09:32:55.910] [undefined] 
Remove all packages in environment C:\Users\dmf\AppData\Local\Programs\InVEST 3.14.2.post387+g366216a2f Workbench\resources\Miniforge3\envs\invest_plugin_schistosomiasis:


[09:32:56.264] [undefined] Preparing transaction: ...working... 
[09:32:56.362] [undefined] done

[09:32:56.363] [undefined] Verifying transaction: ...working... 
[09:32:56.465] [undefined] done

[09:32:56.466] [undefined] Executing transaction: ...working... 
[09:33:16.072] [undefined] done

[09:33:54.091] [undefined] WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(184): Could not remove or rename C:\Users\dmf\AppData\Local\Programs\InVEST 3.14.2.post387+g366216a2f Workbench\resources\Miniforge3\envs\invest_plugin_schistosomiasis\Library\share\proj\proj.db.  Please remove this file manually (you may need to reboot to free file handles)

[09:33:54.134] [undefined] WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(184): Could not remove or rename C:\Users\dmf\AppData\Local\Programs\InVEST 3.14.2.post387+g366216a2f Workbench\resources\Miniforge3\envs\invest_plugin_schistosomiasis\Scripts\invest.exe.  Please remove this file manually (you may need to reboot to free file handles)

[09:33:55.879] [undefined] successfully removed plugin
[09:33:55.911] [undefined] 11/22/2024 09:33:55  natcap.invest.ui_server DEBUG    get model list

[09:33:55.912] [undefined] 11/22/2024 09:33:55  werkzeug           INFO     127.0.0.1 - - [22/Nov/2024 09:33:55] "GET /api/models?language=en HTTP/1.1" 200 -

[09:33:55.926] [undefined] Error: Cannot read properties of undefined (reading 'type')
[09:33:55.927] [undefined] {
  componentStack: '\n' +
    '    at App (file:///C:/Users/dmf/AppData/Local/Programs/InVEST%203.14.2.post414+g69776618d%20Workbench/resources/app.asar/build/assets/index-3d9db23e.js:10925:5)\n' +
    '    at ErrorBoundary (file:///C:/Users/dmf/AppData/Local/Programs/InVEST%203.14.2.post414+g69776618d%20Workbench/resources/app.asar/build/assets/index-3d9db23e.js:11296:5)\n' +
    '    at I18nextWithTranslation (file:///C:/Users/dmf/AppData/Local/Programs/InVEST%203.14.2.post414+g69776618d%20Workbench/resources/app.asar/build/assets/index-3d9db23e.js:3940:31)'
}
```

**Comment by emlys** [comment]
Done in #1781
