### ISSUE TITLE
SQ: "Too Many Open Files" when summing and weighting visibility

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#171]
A user reported the following exception  when running Scenic Quality on InVEST 3.8.2:

```
2020-06-12 12:26:01,428 Task.add_task(626) ERROR Something went wrong when adding task sum_visibility_for_all_structures (7933), terminating taskgraph.
Traceback (most recent call last):
  File "site-packages/taskgraph/Task.py", line 592, in add_task
  File "site-packages/taskgraph/Task.py", line 1069, in _call
  File "site-packages/natcap/invest/scenic_quality/scenic_quality.py", line 874, in _count_and_weight_visible_structures
  File "site-packages/pygeoprocessing/geoprocessing.py", line 295, in raster_calculator
AttributeError: 'NoneType' object has no attribute 'GetRasterBand'
2020-06-12 12:26:01,465 model._logged_target(1635) ERROR Exception while executing <function execute at 0x137a66560>
Traceback (most recent call last):
  File "site-packages/natcap/invest/ui/model.py", line 1632, in _logged_target
  File "site-packages/natcap/invest/scenic_quality/scenic_quality.py", line 426, in execute
  File "site-packages/taskgraph/Task.py", line 592, in add_task
  File "site-packages/taskgraph/Task.py", line 1069, in _call
  File "site-packages/natcap/invest/scenic_quality/scenic_quality.py", line 874, in _count_and_weight_visible_structures
  File "site-packages/pygeoprocessing/geoprocessing.py", line 295, in raster_calculator
AttributeError: 'NoneType' object has no attribute 'GetRasterBand'
2020-06-12 12:26:01,467 model._logged_target(1638) INFO Execution finished
2020-06-12 12:26:01,473 utils.prepare_workspace(117) INFO Elapsed time: 13m 15.649999999999977s
2020-06-12 12:26:01,473 utils.sandbox_tempdir(239) ERROR Could not remove sandbox /Users/shalp/Desktop/ScenicQualityTest/Workspace/tmpbareetuz
Traceback (most recent call last):
  File "site-packages/natcap/invest/utils.py", line 234, in sandbox_tempdir
  File "site-packages/natcap/invest/utils.py", line 114, in prepare_workspace
  File "site-packages/natcap/invest/ui/model.py", line 1632, in _logged_target
  File "site-packages/natcap/invest/scenic_quality/scenic_quality.py", line 426, in execute
  File "site-packages/taskgraph/Task.py", line 592, in add_task
  File "site-packages/taskgraph/Task.py", line 1069, in _call
  File "site-packages/natcap/invest/scenic_quality/scenic_quality.py", line 874, in _count_and_weight_visible_structures
  File "site-packages/pygeoprocessing/geoprocessing.py", line 295, in raster_calculator
AttributeError: 'NoneType' object has no attribute 'GetRasterBand'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/natcap/invest/utils.py", line 237, in sandbox_tempdir
  File "shutil.py", line 516, in rmtree
  File "shutil.py", line 377, in _rmtree_unsafe
  File "shutil.py", line 374, in _rmtree_unsafe
OSError: [Errno 24] Too many open files: '/Users/shalp/Desktop/ScenicQualityTest/Workspace/tmpbareetuz'
```

There are no `osgeo.gdal` errors in the logfile.

Reported on the forums: https://community.naturalcapitalproject.org/t/unobstructed-views-scenic-quality-provision-attributeerror/1062/3

**Comment by phargogh** [comment]
Working on this in branch `bugfix/171-SQ-too-many-open-files`.

Waiting on the actions build https://github.com/phargogh/invest/actions/runs/136631733 to finish so I can send a dev build to the user.
