### ISSUE TITLE
Rec model memory errors 

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#20]
The recreation raises a MemoryError on very large AOIs.

To recreate this issue, create a vector polygon that extends over the continental United States. Then run the model with that single polygon and observe a server-side memory error after a few minutes.

Previous debugging has shown the memory error occurs during the point collection phase where a long list of all covered points is created in memory.

There may be a variety of solutions including an out of core ponit list, an enhanced algorithm that sidesteps the need to maintain a point list in memory, or advanced techniques of subdividing large polygons such that sub polygon's points fit in memory, then combining the result after the fact.

We'll get to this post PyGeoprocessing 1.0 refactor.

Originally reported by @richpsharp at https://bitbucket.org/natcap/invest/issues/3614/rec-model-memory-errors

**Comment by phargogh** [comment]
Is this still relevant?  Leaving open for now.

**Comment by davemfish** [comment]
A different but possibly related out-of-memory error has occurred recently. When the server is processing a large job (consuming > 50% of available memory) and another job is submitted, the latter will fail with

```python
[Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/usr/local/recreation-server/invest/env/lib/python3.7/site-packages/natcap.invest-3.8.8.post374+gd1cac43-py3.7-linux-x86_64.egg/natcap/invest/recreation/recmodel_server.py", line 66, in try_except_wrapper
    return func(*args, **kwargs)
  File "/usr/local/recreation-server/invest/env/lib/python3.7/site-packages/natcap.invest-3.8.8.post374+gd1cac43-py3.7-linux-x86_64.egg/natcap/invest/recreation/recmodel_server.py", line 200, in calc_photo_user_da
ys_in_aoi
    out_vector_filename))
  File "/usr/local/recreation-server/invest/env/lib/python3.7/site-packages/natcap.invest-3.8.8.post374+gd1cac43-py3.7-linux-x86_64.egg/natcap/invest/recreation/recmodel_server.py", line 356, in _calc_aggregated_p
oints_in_aoi
    polytest_process.start()
  File "/usr/local/recreation-server/invest/env/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/usr/local/recreation-server/invest/env/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/local/recreation-server/invest/env/lib/python3.7/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/local/recreation-server/invest/env/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/usr/local/recreation-server/invest/env/lib/python3.7/multiprocessing/popen_fork.py", line 70, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
```

It seems `os.fork` wants to create a clone of the parent process, including all the memory it's already using. So if that happens during a large job, there won't be memory available for the new process.

**Comment by davemfish** [comment]
`spawn` instead of `fork` does seem to reduce memory demands. Swapping them out in the server launch script like this:

```python
if __name__ == '__main__':
    multiprocessing.set_start_method('fork')
    natcap.invest.recreation.recmodel_server.execute(args)
```

Testing on my linux laptop, the recmodel found 4 CPUs. Much of the server-side code runs in the main process, but then multiple child processes are started for the point in polygon tests. 

According to `top`:

###Fork:
The main server process uses ~12% of memory, then `forks` 4 children, each use 11.4%.
A second client job is launched (smaller AOI), it's 4 `forks` each use ~14%.

###Spawn:
The main server process uses ~12% of memory, then `spawns` 4 children, each use ~2.6%.
A second client job is launched (smaller AOI), it's 4 `spawns` each use ~2.4%.

As mentioned in the original post of this issue, most memory is consumed by building a list of points covered by the AOI. That happens before the child processes are started. But it seems clear that using `spawn` avoids the problem of copying all that memory to the child process. The children don't need that list object in memory, they work with a local quadtree already on disk.

An earlier profile I tried using `tracemalloc`, I found a server started with `spawn` had a peak memory usage ~6x higher than the peak for a server started with `fork`. That's counterintuitive so I'm guessing that I didn't use `tracemalloc` properly.
