### ISSUE TITLE
CV interpolate_shore_points: "No Shapely geometry can be created from null value"

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#347]
A user on the forums posted a [conversation on the forums](https://community.naturalcapitalproject.org/t/no-shapely-geometry-can-be-created-from-null-value-invest-cv/1421/2) with the following error(s) in the logfile :

```python
2020-10-15 19:33:15,269 coastal_vulnerability.prepare_landmass_line_index(623) INFO preparing landmass geometry
2020-10-15 23:11:22,210 coastal_vulnerability.prepare_landmass_line_index(643) INFO indexing geometry of landmass
2020-10-15 23:22:20,172 coastal_vulnerability.interpolate_shore_points(674) INFO creating shore points along edge of landmass
2020-10-15 23:27:23,501 geos.callback(209) ERROR bad allocation
2020-10-15 23:27:23,501 Task.add_task(731) ERROR Something went wrong when adding task create shore points (3), terminating taskgraph.
Traceback (most recent call last):
  File "site-packages\taskgraph\Task.py", line 697, in add_task
  File "site-packages\taskgraph\Task.py", line 1174, in _call
  File "site-packages\natcap\invest\coastal_vulnerability.py", line 704, in interpolate_shore_points
  File "site-packages\shapely\ops.py", line 115, in linemerge
  File "site-packages\shapely\geometry\base.py", line 76, in geom_factory
ValueError: No Shapely geometry can be created from null value
2020-10-15 23:27:23,503 model._logged_target(1632) ERROR Exception while executing <function execute at 0x1ADC49C0>
Traceback (most recent call last):
  File "site-packages\natcap\invest\ui\model.py", line 1629, in _logged_target
  File "site-packages\natcap\invest\coastal_vulnerability.py", line 393, in execute
  File "site-packages\taskgraph\Task.py", line 697, in add_task
  File "site-packages\taskgraph\Task.py", line 1174, in _call
  File "site-packages\natcap\invest\coastal_vulnerability.py", line 704, in interpolate_shore_points
  File "site-packages\shapely\ops.py", line 115, in linemerge
  File "site-packages\shapely\geometry\base.py", line 76, in geom_factory
ValueError: No Shapely geometry can be created from null value
2020-10-15 23:27:23,503 model._logged_target(1635) INFO Execution finished
2020-10-15 23:27:23,508 utils.prepare_workspace(117) INFO Elapsed time: 4h 6m 8.530000000000655s
```

Somehow, a null geometry is getting through to the [`shapely.ops.linemerge` call](https://github.com/natcap/invest/blob/release/3.9/src/natcap/invest/coastal_vulnerability.py#L713).  I've requested the user's data and am waiting to hear back from them.  I could make an educated guess about null geometries, but I'd rather see what the issue is first before implementing a fix.

**Comment by emlys** [comment]
It looks like this forum convo was resolved and the problem was that the user's AOI was too far away from the WWIII data. @phargogh, @davemfish, do you remember if any changes to CV were needed in the end? Can this issue be closed?

**Comment by phargogh** [comment]
I don't think we've seen this issue since the linked forums discussion, so I'd be open to closing it!  @davemfish were there any changes made to the model as a result of this discussion?

**Comment by davemfish** [comment]
I don't have any specific memory of this issue. Reading the thread, it sounds like James concluded this issue was resolved:

>Thanks for your data! I’ve been running the model (minus geomorphology) on your inputs and am currently unable to reproduce this issue using the latest development build. Could you try running CV on the latest development build, linked below and let us know how it goes? I have a suspicion that this might have been fixed with an update in one of the libraries that InVEST uses for geometric operations.

So I think we're good to close it.
