### ISSUE TITLE
CV Memory error

### ISSUE THREAD

**Issue by dcdenu4** [natcap/invest#352]
There's a user that reported a memory error in CV. I was able to reproduce the error below:
https://community.naturalcapitalproject.org/t/coastal-vulnerability-memory-error/1430/9
```python
2020-10-21 13:57:29,379 validation.timeout(638) INFO File checking thread completed.
2020-10-21 13:57:39,231 geos.callback(209) ERROR IllegalArgumentException: Points of LinearRing do not form a closed linestring
2020-10-21 13:57:39,235 coastal_vulnerability._ogr_to_geometry_list(2732) WARNING Could not load feature 95 of C:/Users/ddenu/Workspace/NatCap/User-Data/megc-cv-10-21-2020/InVEST Coastal Vulnerabilty Data-20201021T151429Z-001/InVEST Coastal Vulnerabilty Data/global_polygon.shp
2020-10-21 13:57:40,440 geos.callback(209) ERROR IllegalArgumentException: Points of LinearRing do not form a closed linestring
2020-10-21 13:57:40,441 coastal_vulnerability._ogr_to_geometry_list(2732) WARNING Could not load feature 491 of C:/Users/ddenu/Workspace/NatCap/User-Data/megc-cv-10-21-2020/InVEST Coastal Vulnerabilty Data-20201021T151429Z-001/InVEST Coastal Vulnerabilty Data/global_polygon.shp
2020-10-21 14:05:48,248 geoprocessing.reproject_vector(1640) INFO starting reprojection
2020-10-21 14:05:51,494 geoprocessing.reproject_vector(1683) INFO reprojection 100.0% complete on clipped_projected_landmass.gpkg
2020-10-21 14:05:53,456 coastal_vulnerability.warp_and_mask_bathymetry(1707) INFO Masking positive values from bathymetry
2020-10-21 14:05:56,607 coastal_vulnerability.clip_and_project_raster(2424) WARNING C:/Users/ddenu/Workspace/NatCap/User-Data/megc-cv-10-21-2020/InVEST Coastal Vulnerabilty Data-20201021T151429Z-001/InVEST Coastal Vulnerabilty Data/global_dem.tif is unprojected and will be warped to match the AOI and resampled to a pixel size of 10000 meters
2020-10-21 14:05:58,701 geoprocessing.raster_calculator(375) INFO starting stats_worker
2020-10-21 14:05:58,703 geoprocessing.raster_calculator(381) INFO started stats_worker <Thread(Thread-269, started daemon 22984)>
2020-10-21 14:05:58,922 geoprocessing.raster_calculator(454) INFO 100.0%% complete2020-10-21 15:12:28,466 coastal_vulnerability.prepare_landmass_line_index(643) INFO indexing geometry of landmass
2020-10-21 15:31:41,140 coastal_vulnerability.interpolate_shore_points(674) INFO creating shore points along edge of landmass
2020-10-21 15:39:37,309 Task.add_task(731) ERROR Something went wrong when adding task create shore points (3), terminating taskgraph.
Traceback (most recent call last):
  File "site-packages\taskgraph\Task.py", line 697, in add_task
  File "site-packages\taskgraph\Task.py", line 1174, in _call
  File "site-packages\natcap\invest\coastal_vulnerability.py", line 704, in interpolate_shore_points
  File "site-packages\shapely\ops.py", line 114, in linemerge
  File "site-packages\shapely\geometry\proxy.py", line 30, in _geom
  File "site-packages\shapely\geometry\proxy.py", line 39, in gtag
MemoryError
2020-10-21 15:39:37,311 model._logged_target(1632) ERROR Exception while executing <function execute at 0x18FE5978>
Traceback (most recent call last):
  File "site-packages\natcap\invest\ui\model.py", line 1629, in _logged_target
  File "site-packages\natcap\invest\coastal_vulnerability.py", line 393, in execute
  File "site-packages\taskgraph\Task.py", line 697, in add_task
  File "site-packages\taskgraph\Task.py", line 1174, in _call
  File "site-packages\natcap\invest\coastal_vulnerability.py", line 704, in interpolate_shore_points
  File "site-packages\shapely\ops.py", line 114, in linemerge
  File "site-packages\shapely\geometry\proxy.py", line 30, in _geom
  File "site-packages\shapely\geometry\proxy.py", line 39, in gtag
MemoryError
2020-10-21 15:39:37,313 model._logged_target(1635) INFO Execution finished
2020-10-21 15:39:37,315 utils.prepare_workspace(117) INFO Elapsed time: 1h 42m 8.11999999999989s
2020-10-21 15:39:37,325 execution.run(78) ERROR Target <function InVESTModel.execute_model.<locals>._logged_target at 0x1A54B9C0> failed with exception
Traceback (most recent call last):
  File "site-packages\natcap\invest\ui\execution.py", line 68, in run
  File "site-packages\natcap\invest\ui\model.py", line 1629, in _logged_target
  File "site-packages\natcap\invest\coastal_vulnerability.py", line 393, in execute
  File "site-packages\taskgraph\Task.py", line 697, in add_task
  File "site-packages\taskgraph\Task.py", line 1174, in _call
  File "site-packages\natcap\invest\coastal_vulnerability.py", line 704, in interpolate_shore_points
  File "site-packages\shapely\ops.py", line 114, in linemerge
  File "site-packages\shapely\geometry\proxy.py", line 30, in _geom
  File "site-packages\shapely\geometry\proxy.py", line 39, in gtag
MemoryError
2020-10-21 15:39:37,326 execution.run(83) INFO Execution finished

2020-10-21 14:05:58,923 geoprocessing.raster_calculator(457) INFO signaling stats worker to terminate
2020-10-21 14:05:58,923 geoprocessing.raster_calculator(459) INFO Waiting for raster stats worker result.
2020-10-21 14:05:59,323 coastal_vulnerability.prepare_landmass_line_index(623) INFO preparing landmass geometry
```

**Comment by dcdenu4** [comment]
This occurs when trying to run CV on global data with a global AOI. But, the model shouldn't crash on a memory error.

**Comment by dcdenu4** [comment]
The memory error is occurring in `def interpolate_shore_points` on the lines:

```python
shapely_geom_explode = [shapely.geometry.LineString(x) for x in intersected_shapely_geom]
```

**Comment by dcdenu4** [comment]
The memory issue is not noticeable with the 64-bit builds but is with the 32-bit builds.

**Comment by dcdenu4** [comment]
**Update**
The memory failure is actually on the `shapely.ops.linemerge` call and NOT the above mentioned list comprehension. From what I can gather so far, during shore point interpolation function on a global run, the `linestring` geometries build up in a list and then when asked to do a merge on them, blows up.

One working prototype I have for a fix is to chunk up the entire process including interpolating points over the line geometries. Doing this keeps the amount of `linestring` objects building up to a minimum, BUT does cause the interpolating points to be "off".

**Comment by dcdenu4** [comment]
After talking with @davemfish we decided that a good solution going forward would be to move the functionality of `interpolate_shore_points` into `prepare_landmass_line_index`. The reason for this is to allow the sharing of knowledge of which lines come from which landmass polygons without having to make redundant calls or data structures.

**Comment by dcdenu4** [comment]
This was merged in, should be good!
