### ISSUE TITLE
Habitat Quality convolution memory error

### ISSUE THREAD

**Issue by dcdenu4** [natcap/invest#353]
A user on the forums reported a memory error when running Habitat Quality. The memory error occurs in the convolution step and could be a pygeoprocessing bug. The kernel the user was attempting to run was created from `utils.exponential_decay_kernel_raster` with an `expected_distance` of  `4757` pixels. The kernel raster generated was 8.8 GBs in size.

User forum post: https://community.naturalcapitalproject.org/t/filenotfounderror-winerror-2/1408/7

```python
2020-10-21 00:09:21,985 threading.run(870) DEBUG payload is None, terminating
2020-10-21 00:09:22,465 habitat_quality.execute(481) INFO Calculating threat: m_explot.
Threat data: {'THREAT': 'm_explot', 'MAX_DIST': 47.57, 'WEIGHT': 0.52, 'DECAY': 'exponential'}
2020-10-21 00:09:22,467 habitat_quality.execute(485) INFO threat_raster_path C:/Users/RRomo/Desktop/InVEST_Planet2018_reescalado\intermediate\m_explot_c_aligned.tif
2020-10-21 00:09:22,515 habitat_quality.execute(508) DEBUG Max distance in pixels: 4757.000000
2020-10-21 00:13:21,622 geoprocessing.convolve_2d(2422) INFO starting convolve
2020-10-21 01:19:42,937 utils._log_gdal_errors(68) ERROR [errno 1] C:/Users/RRomo/Desktop/InVEST_Planet2018_reescalado\intermediate\kernels\kernel_m_explot_c.tif:Failed to allocate memory for TIFFReadDirEntryArray (1 elements of 276768 bytes each)
2020-10-21 01:19:42,988 utils._log_gdal_errors(68) ERROR [errno 1] TIFFFetchStripThing:Out of memory reading of "TileByteCounts"
2020-10-21 01:19:43,017 model._logged_target(1632) ERROR Exception while executing <function execute at 0x1B315540>
Traceback (most recent call last):
  File "site-packages\natcap\invest\ui\model.py", line 1629, in _logged_target
  File "site-packages\natcap\invest\habitat_quality.py", line 531, in execute
  File "site-packages\pygeoprocessing\geoprocessing.py", line 2454, in convolve_2d
  File "site-packages\pygeoprocessing\geoprocessing.py", line 2636, in iterblocks
ValueError: Raster at C:/Users/RRomo/Desktop/InVEST_Planet2018_reescalado\intermediate\kernels\kernel_m_explot_c.tif could not be opened.
2020-10-21 01:19:43,088 model._logged_target(1635) INFO Execution finished
2020-10-21 01:19:43,126 utils.prepare_workspace(117) INFO Elapsed time: 13h 42m 31.05000000000291s
```

**Comment by dcdenu4** [comment]
Currently making some sample data to reproduce this bug and then ping Rich.

**Comment by dcdenu4** [comment]
This has been fixed in pygeoprocessing https://github.com/natcap/pygeoprocessing/pull/126
