### ISSUE TITLE
Habitat Quality FileNotFoundError python race condition

### ISSUE THREAD

**Issue by dcdenu4** [natcap/invest#355]
A user posted a fun error they had when running a large dataset on the HQ model. This is a pretty strange issue because the call that is seemingly failing is trying to delete a file that has already been deleted. This looks like a possible race condition between two calls and maybe even a documented Python bug: https://bugs.python.org/issue29699

The user ran the model again and did not encounter the issue.

User Post:
https://community.naturalcapitalproject.org/t/filenotfounderror-winerror-2/1408

```python
2020-10-10 00:13:34,508 geoprocessing.<lambda>(2561) INFO convolution nodata normalizer approximately 98.7% complete on filtered_ag_per_c.tif
2020-10-10 00:13:36,506 geoprocessing.convolve_2d(2568) INFO convolution nodata normalize 100.0% complete on filtered_ag_per_c.tif
2020-10-10 00:13:37,047 model._logged_target(1632) ERROR Exception while executing <function execute at 0x1C221540>
Traceback (most recent call last):
  File "site-packages\natcap\invest\ui\model.py", line 1629, in _logged_target
  File "site-packages\natcap\invest\habitat_quality.py", line 531, in execute
  File "site-packages\pygeoprocessing\geoprocessing.py", line 2580, in convolve_2d
  File "shutil.py", line 516, in rmtree
  File "shutil.py", line 400, in _rmtree_unsafe
  File "shutil.py", line 398, in _rmtree_unsafe
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado: 'C:\\Users\\RRomo\\AppData\\Local\\Temp\\tmpuwwh4_ng\\convolved_mask.tif'
2020-10-10 00:13:37,085 model._logged_target(1635) INFO Execution finished
2020-10-10 00:13:38,742 utils.prepare_workspace(117) INFO Elapsed time: 14h 7m 16.290000000000873s
```

**Comment by dcdenu4** [comment]
This has been fixed in pygeoprocessing : https://github.com/natcap/pygeoprocessing/pull/131
