### ISSUE TITLE
Validation: check spatial overlap on layer with no projection

### ISSUE THREAD

**Issue by davemfish** [natcap/invest#519]
If a layer's projection wkt is `None`, `check_spatial_overlap` errors like this:

```
Traceback (most recent call last):
  File "site-packages\natcap\invest\ui\model.py", line 1649, in _logged_target
  File "site-packages\natcap\invest\coastal_vulnerability.py", line 286, in execute
  File "site-packages\natcap\invest\validation.py", line 916, in _wrapped_validate_func
  File "site-packages\natcap\invest\coastal_vulnerability.py", line 2952, in validate
  File "site-packages\natcap\invest\validation.py", line 843, in validate
  File "site-packages\natcap\invest\validation.py", line 580, in check_spatial_overlap
  File "site-packages\pygeoprocessing\geoprocessing.py", line 2878, in transform_bounding_box
  File "site-packages\osgeo\osr.py", line 891, in ImportFromWkt
TypeError: not a string
```

Validation does check if the SRS is `None` during the `check_vector` and `check_raster` steps. They append a validation message when SRS is None, but validation continues to `check_spatial_overlap`. And since that func raises an uncaught error, we never get to see the validation message reported from `check_vector`.

If this happens in the UI, I think the model is allowed to run because no validation messages are returned. CV caught this issue because it happens to call `validate` during `execute` (questionable but useful here!).

**Comment by phargogh** [comment]
Yep, that makes sense that the model would run if there's an exception.

In the case of CV, are there any cases where a spatial reference is allowed to be undefined?

**Comment by davemfish** [comment]
> In the case of CV, are there any cases where a spatial reference is allowed to be undefined?

No, I can't think of any case where that would be okay in any model.
