### ISSUE TITLE
GDAL 3.3.0 breaks InVEST binary builds

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#550]
GDAL 3.3.0 was released about 2 weeks ago, and when I attempt to do an InVEST binary build on Windows, I get the following exception ([source GHA build](https://github.com/phargogh/invest/runs/2606981118?check_suite_focus=true)):

```python
dist/invest/invest list
Traceback (most recent call last):
  File "natcap\invest\cli.py", line 19, in <module>
ImportError: attempted relative import with no known parent package

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "osgeo\__init__.py", line 18, in swig_import_helper
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'osgeo._gdal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "natcap\invest\cli.py", line 24, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "natcap\invest\__init__.py", line 8, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "pygeoprocessing\__init__.py", line 9, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "pygeoprocessing\geoprocessing.py", line 16, in <module>
  File "src\pygeoprocessing\geoprocessing_core.pyx", line 26, in init pygeoprocessing.geoprocessing_core
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "osgeo\__init__.py", line 34, in <module>
  File "osgeo\__init__.py", line 30, in swig_import_helper
ImportError: Traceback (most recent call last):
  File "natcap\invest\cli.py", line 19, in <module>
ImportError: attempted relative import with no known parent package

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "osgeo\__init__.py", line 18, in swig_import_helper
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'osgeo._gdal'

On Windows, with Python >= 3.8, DLLs are no longer imported from the PATH.
If gdalXXX.dll is in the PATH, then set the USE_PATH_FOR_GDAL_PYTHON=YES environment variable
to feed the PATH into os.add_dll_directory().
```

We do indeed build InVEST binaries on python 3.8, so this new behavior does affect us.  So far I tried two separate possible fixes for this without success and with various errors:

1. https://github.com/phargogh/invest/commit/e183f14fa1fe65bbae36849e707fc44a6c2151a4 ([build results](https://github.com/phargogh/invest/runs/2611381465))
2. https://github.com/phargogh/invest/commit/ed721e923c07f9c0439d176f5b8e82c536d07123 ([build results](https://github.com/phargogh/invest/runs/2611585568))

Until we've had a chance to fix this properly, I've capped the GDAL version to `<3.3.0` in `requirements.txt` (https://github.com/phargogh/invest/commit/71dcdc413b79d9ae6aacf064db90e0e31b70939e)

**Comment by emlys** [comment]
I'm seeing a similar issue in pygeoprocessing, in the windows/python3.7/gdal3.0.4 test: https://github.com/natcap/pygeoprocessing/pull/196/checks?check_run_id=2668524313#step:7:63
