### ISSUE TITLE
Mac binaries failing with RTree DLL issue on import

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#594]
The Mac binaries on `main` have been failing with an RTree-related error on import:

```
dist/invest/invest list
Traceback (most recent call last):
  File "natcap/invest/cli.py", line 19, in <module>
ImportError: attempted relative import with no known parent package

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "natcap/invest/cli.py", line 24, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "natcap/invest/__init__.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "pygeoprocessing/__init__.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "pygeoprocessing/geoprocessing.py", line 23, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "rtree/__init__.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "rtree/index.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "rtree/core.py", line 77, in <module>
  File "ctypes/__init__.py", line 386, in __getattr__
  File "ctypes/__init__.py", line 391, in __getitem__
AttributeError: dlsym(RTLD_DEFAULT, Error_GetLastErrorNum): symbol not found
[6951] Failed to execute script 'cli' due to unhandled exception!
```

Failures seem to appear around PR #582 and are not present in the tests.  A quick look at the conda package diffing in the tests show consistent conda package versions of RTree and libspatialindex being used between passing and failing mac builds, so this is probably not a package version issue.

**Comment by phargogh** [comment]
Although [this rtree issue](https://github.com/Toblerity/rtree/issues/37)
