### ISSUE TITLE
Execution error with sample date - ValueError: Null geometry supports no operations

### ISSUE THREAD

**Issue by g2giovanni** [natcap/invest#635]
I'm trying to execute the Urban Cooling model with sample data but the execution fails with the following error:

```
09/08/2021 01:24:28  geos.callback(252) ERROR IllegalArgumentException: Shell is not a LinearRing
09/08/2021 01:24:28  geos.callback(252) ERROR IllegalArgumentException: PreparedGeometry constructed with null Geometry object
09/08/2021 01:24:28  geoprocessing.calculate_disjoint_polygon_set(2253) INFO build shapely rtree index
09/08/2021 01:24:28  Task.add_task(779) ERROR Something went wrong when adding task pickle cc ref stats (14), terminating taskgraph.
Traceback (most recent call last):
  File "/Users/g2giovanni/Library/Caches/pypoetry/virtualenvs/invest-models-H0SMhV8F-py3.8/lib/python3.8/site-packages/taskgraph/Task.py", line 747, in add_task
    new_task._call()
  File "/Users/g2giovanni/Library/Caches/pypoetry/virtualenvs/invest-models-H0SMhV8F-py3.8/lib/python3.8/site-packages/taskgraph/Task.py", line 1234, in _call
    payload = self._func(*self._args, **self._kwargs)
  File "/Users/g2giovanni/Library/Caches/pypoetry/virtualenvs/invest-models-H0SMhV8F-py3.8/lib/python3.8/site-packages/natcap/invest/urban_cooling_model.py", line 1066, in pickle_zonal_stats
    zonal_stats = pygeoprocessing.zonal_statistics(
  File "/Users/g2giovanni/Library/Caches/pypoetry/virtualenvs/invest-models-H0SMhV8F-py3.8/lib/python3.8/site-packages/pygeoprocessing/geoprocessing.py", line 1283, in zonal_statistics
    disjoint_fid_sets = calculate_disjoint_polygon_set(
  File "/Users/g2giovanni/Library/Caches/pypoetry/virtualenvs/invest-models-H0SMhV8F-py3.8/lib/python3.8/site-packages/pygeoprocessing/geoprocessing.py", line 2254, in calculate_disjoint_polygon_set
    r_tree_index_stream = [
  File "/Users/g2giovanni/Library/Caches/pypoetry/virtualenvs/invest-models-H0SMhV8F-py3.8/lib/python3.8/site-packages/pygeoprocessing/geoprocessing.py", line 2257, in <listcomp>
    if bounding_box.intersects(poly)]
  File "/Users/g2giovanni/Library/Caches/pypoetry/virtualenvs/invest-models-H0SMhV8F-py3.8/lib/python3.8/site-packages/shapely/impl.py", line 37, in wrapper
    return func(*args, **kwargs)
  File "/Users/g2giovanni/Library/Caches/pypoetry/virtualenvs/invest-models-H0SMhV8F-py3.8/lib/python3.8/site-packages/shapely/prepared.py", line 76, in intersects
    return bool(self.impl['prepared_intersects'](self, other))
  File "/Users/g2giovanni/Library/Caches/pypoetry/virtualenvs/invest-models-H0SMhV8F-py3.8/lib/python3.8/site-packages/shapely/predicates.py", line 12, in __call__
    self._validate(this)
  File "/Users/g2giovanni/Library/Caches/pypoetry/virtualenvs/invest-models-H0SMhV8F-py3.8/lib/python3.8/site-packages/shapely/topology.py", line 18, in _validate
    raise ValueError("Null geometry supports no operations")
ValueError: Null geometry supports no operations
```

The execution ends with no fails if I execute from the Windows client. 
Following the code I used:

```python
# coding=UTF-8
# -----------------------------------------------
# Generated by InVEST 3.9.0 on Tue Sep  7 13:42:50 2021
# Model: Urban Cooling Model

import logging
import sys

import natcap.invest.urban_cooling_model
import natcap.invest.utils

LOGGER = logging.getLogger(__name__)
root_logger = logging.getLogger()

handler = logging.StreamHandler(sys.stdout)
formatter = logging.Formatter(
    fmt=natcap.invest.utils.LOG_FMT,
    datefmt='%m/%d/%Y %H:%M:%S ')
handler.setFormatter(formatter)
logging.basicConfig(level=logging.DEBUG, handlers=[handler])

ROOT_PATH = '/Users/myuser/Desktop/InVEST_Models/sample_data/UrbanCoolingModel'

args = {
    'aoi_vector_path': ROOT_PATH + '/aoi.shp',
    'avg_rel_humidity': '30',
    'results_suffix': '_sample',
    'biophysical_table_path': ROOT_PATH + '/Biophysical_UHI_fake.csv',
    'building_vector_path': ROOT_PATH + '/sample_buildings.shp',
    'cc_method': 'factors',
    'cc_weight_albedo': '0.2',
    'cc_weight_eti': '0.2',
    'cc_weight_shade': '0.6',
    'do_energy_valuation': True,
    'do_productivity_valuation': True,
    'energy_consumption_table_path': ROOT_PATH + '/Fake_energy_savings.csv',
    'green_area_cooling_distance': '500',
    'lulc_raster_path': ROOT_PATH + '/lulc.tif',
    'ref_eto_raster_path': ROOT_PATH + '/et0.tif',
    'results_suffix': '_sample',
    't_air_average_radius': '600',
    't_ref': '21.5',
    'uhi_max': '3.5',
    'workspace_dir': '/Users/myuser/Desktop/InVEST_Models/UrbanCooling/runs/urban_cooling_model_workspace_2',
}

if __name__ == '__main__':
    natcap.invest.urban_cooling_model.execute(args)

```

**Comment by emlys** [comment]
Hi @g2giovanni, I could not replicate this on my mac using your script with invest 3.9.0 and the sample data. Could you please share your complete environment listing (`pip list` or `conda list`)? I wonder if you have a version of shapely or something that we haven't tested.

**Comment by g2giovanni** [comment]
I installed natcap.invest using Poetry. Following the list of the packages:

```
attrs           21.2.0  Classes Without Boilerplate
chardet         4.0.0   Universal encoding detector for Python 2 and 3
cython          0.29.24 The Cython compiler for writing C extensions for th...
gdal            3.3.2   GDAL: Geospatial Data Abstraction Library
more-itertools  8.9.0   More routines for operating on iterables, beyond it...
natcap.invest   3.9.0   InVEST Ecosystem Service models
numpy           1.21.1  NumPy is the fundamental package for array computin...
packaging       21.0    Core utilities for Python packages
pandas          1.3.2   Powerful data structures for data analysis, time se...
pluggy          0.13.1  plugin and hook calling mechanisms for python
psutil          5.8.0   Cross-platform lib for process and system monitorin...
py              1.10.0  library with cross-python path, ini-parsing, io, co...
pygeoprocessing 2.3.1   PyGeoprocessing: Geoprocessing routines for GIS
pyparsing       2.4.7   Python parsing module
pyro4           4.77    distributed object middleware for Python (RPC)
pytest          5.4.3   pytest: simple powerful testing with Python
python-dateutil 2.8.2   Extensions to the standard Python datetime module
pytz            2021.1  World timezone definitions, modern and historical
retrying        1.3.3   Retrying
rtree           0.9.7   R-Tree spatial index for Python GIS
scipy           1.4.1   SciPy: Scientific Library for Python
serpent         1.40    Serialization based on ast.literal_eval
shapely         1.7.1   Geometric objects, predicates, and operations
six             1.16.0  Python 2 and 3 compatibility utilities
taskgraph       0.10.3  Parallel task graph framework.
wcwidth         0.2.5   Measures the displayed width of unicode strings in ...
xlrd            2.0.1   Library for developers to extract data from Microso...
xlwt            1.3.0   Library to create spreadsheet files compatible with
```

**Comment by emlys** [comment]
I notice a few packages do not meet the requirements in `requirements.py` for invest 3.9.0:
- you have GDAL 3.3.2, but invest 3.9.0 requires `GDAL>=3.1.2,<3.3.0`
- you have scipy 1.4.1, but invest 3.9.0 requires `scipy>=1.6.0`
- you have pygeoprocessing 2.3.1, but invest 3.9.0 requires `pygeoprocessing>=2.1.1,<2.2.0`

Please try using versions within these constraints and let us know if that fixes the problem! 

Out of curiosity, did you manually add any dependencies besides `natcap.invest` or did Poetry choose them all? I would be interested if there's an easy way we can make our requirements files compatible with Poetry.

**Comment by emlys** [comment]
If you wish to keep using invest 3.9.0 and not the latest (unreleased) version, just switching to `GDAL==3.1.2` and `pygeoprocessing>=2.1.1` should be enough. GDAL 3.3.0 was released after invest 3.9.0, so we were unaware of that upper bound at the time. 

@phargogh, this makes me wonder if we should start setting an upper bound on every dependency, to the latest version that we've tested with at the time of a release? I know we've tried to be as unrestrictive as possible with dependencies. But with enough time, `pip install natcap.invest==<old version>` will always eventually break as dependencies get non-backwards-compatible updates. I was hoping `pip install` would have some option to install the minimum allowed version of each dependency instead of the maximum, but I'm not finding one.

**Comment by g2giovanni** [comment]
I pip installed from git repository ( `pip install git+https://github.com/natcap/invest@main` ) but I have the same problem.
This is the list of the packages now: 

```
attrs           21.2.0                          Classes Without Boilerplate
chardet         4.0.0                           Universal encoding detector for Pyt...
cython          0.29.24                         The Cython compiler for writing C e...
et-xmlfile      1.1.0                           An implementation of lxml.xmlfile f...
gdal            3.2.3                           GDAL: Geospatial Data Abstraction L...
more-itertools  8.9.0                           More routines for operating on iter...
natcap.invest   3.9.0.post449+g4d0fbcb4 4d0fbcb InVEST Ecosystem Service models
numpy           1.21.1                          NumPy is the fundamental package fo...
openpyxl        3.0.7                           A Python library to read/write Exce...
packaging       21.0                            Core utilities for Python packages
pandas          1.3.2                           Powerful data structures for data a...
pluggy          0.13.1                          plugin and hook calling mechanisms ...
psutil          5.8.0                           Cross-platform lib for process and ...
py              1.10.0                          library with cross-python path, ini...
pygeoprocessing 2.1.2                           PyGeoprocessing: Geoprocessing rout...
pyparsing       2.4.7                           Python parsing module
pyro4           4.77                            distributed object middleware for P...
pytest          5.4.3                           pytest: simple powerful testing wit...
python-dateutil 2.8.2                           Extensions to the standard Python d...
pytz            2021.1                          World timezone definitions, modern ...
retrying        1.3.3                           Retrying
rtree           0.9.7                           R-Tree spatial index for Python GIS
scipy           1.6.1                           SciPy: Scientific Library for Python
serpent         1.40                            Serialization based on ast.literal_...
shapely         1.7.1                           Geometric objects, predicates, and ...
six             1.16.0                          Python 2 and 3 compatibility utilities
taskgraph       0.10.3                          Parallel task graph framework.
wcwidth         0.2.5                           Measures the displayed width of uni...
```

**Comment by phargogh** [comment]
@emlys you bring up a good point about putting a version cap on the package versions.  We could also explore using pip's [compatible release syntax](https://www.python.org/dev/peps/pep-0440/#compatible-release) (`gdal~=3.2`), which might be easier than setting an upper bound.  In any case, the larger point still holds which is that folks tend to use InVEST as an application rather than a library and maybe it's time we manage our dependencies that way.  I've added your comment to the existing dependency-management issue at https://github.com/natcap/invest/issues/191#issuecomment-915513422, so maybe we can follow up about this issue over there?

**Comment by phargogh** [comment]
@g2giovanni I know you said that you're running InVEST on the sample data, but the part of the logfile you included in the issue post could be data-related rather than package-related.  Somehow, the model is ending up with an empty geometry.

Could you include the complete logging from your InVEST run?  If there's a lot of stdout, you could just put it in a `.txt` file and attach that, or else feel free to add a filehandler to your logger, like so:

```python
filehandler = logging.FileHandler('logfile.txt', mode='w')
filehandler.setFormatter(formatter)
logging.basicConfig(level=logging.DEBUG, handlers=[handler, filehandler])
```

**Comment by g2giovanni** [comment]
I solved the problem. The problem was in the dependencies installation. In particular, I had GDAL 3.2.2 python library properly installed but on my Mac I had GDAL 3.3.1 binary. 
Creating a new environment with Conda + Pip solved the problem.
Following the list of commands I used:

`` `
conda create -n invest python=3.8
conda activate invest
conda config --env --add channels conda-forge
conda config --env --set channel_priority strict 
conda install “gdal=3.2.2” rtree shapely numpy cython scipy
pip install natcap.invest
```

**Comment by dcdenu4** [comment]
>Somehow, the model is ending up with an empty geometry.

I noticed this too and checked the Urban Cooling model sample data vectors in QGIS for invalid geometries. They all checked out. Made a new issue to keep an eye on this when going to support GDAL 3.3.0 #637
