### ISSUE TITLE
HRA: Traceback is not written to the logfile

### ISSUE THREAD

**Issue by davemfish** [natcap/invest#651]
On `main`, running HRA with the sample data yields this output on stdout + stderr streams

```
(C:\Users\dmf\projects\invest\env) λ invest --debug run --headless hra -d data\invest-sample-data\HabitatRiskAssess\hra_wcvi.invs.json -w runs/hra
09/17/2021 10:39:50  natcap.invest.cli  INFO     Imported target natcap.invest.hra from <module 'natcap.invest.hra' from 'C:\\Users\\dmf\\projects\\invest\\env\\lib\\site-packages\\natcap.invest-3.9.0.post537+g8652471a-py3.8-win-amd64.egg\\natcap\\invest\\hra.py'>
09/17/2021 10:39:50  natcap.invest.utils INFO     Writing log messages to runs/hra\InVEST-natcap.invest.hra-log-2021-09-17--10_39_50.txt
09/17/2021 10:39:50  natcap.invest.cli  Level 100 Starting model with parameters:
Arguments for InVEST natcap.invest.hra 3.9.0.post537+g8652471a:
aoi_vector_path     C:\Users\dmf\projects\invest\data\invest-sample-data\HabitatRiskAssess\Input\subregions.shp
criteria_table_path C:\Users\dmf\projects\invest\data\invest-sample-data\HabitatRiskAssess\Input\exposure_consequence_criteria.csv
decay_eq            Linear
info_table_path     C:\Users\dmf\projects\invest\data\invest-sample-data\HabitatRiskAssess\Input\habitat_stressor_info.csv
max_rating          3
resolution          500
results_suffix
risk_eq             Euclidean
visualize_outputs   True
workspace_dir       runs/hra

09/17/2021 10:39:50  natcap.invest.hra  INFO     Validating arguments
09/17/2021 10:39:50  natcap.invest.validation DEBUG    Using ARG_SPEC for validation
09/17/2021 10:39:50  natcap.invest.validation INFO     Starting whole-model validation with ARGS_SPEC
09/17/2021 10:39:50  natcap.invest.validation DEBUG    Starting file checking thread with timeout=5
09/17/2021 10:39:50  natcap.invest.validation DEBUG    File checking thread completed.
09/17/2021 10:39:50  natcap.invest.validation DEBUG    Starting file checking thread with timeout=5
09/17/2021 10:39:50  natcap.invest.validation DEBUG    File checking thread completed.
09/17/2021 10:39:50  natcap.invest.validation DEBUG    Starting file checking thread with timeout=5
09/17/2021 10:39:50  natcap.invest.validation DEBUG    File checking thread completed.
09/17/2021 10:39:50  natcap.invest.validation DEBUG    Starting file checking thread with timeout=5
09/17/2021 10:39:50  natcap.invest.validation DEBUG    File checking thread completed.
09/17/2021 10:39:50  natcap.invest.validation DEBUG    Validation warnings: []
09/17/2021 10:39:50  natcap.invest.hra  INFO     Validating criteria table file and return cleaned dataframe.
09/17/2021 10:39:50  natcap.invest.hra  INFO     Criteria dataframe was created successfully.
09/17/2021 10:39:51  taskgraph.Task     DEBUG    file:///C:/Users/dmf/projects/invest/runs/hra/intermediate_outputs/_taskgraph_working_dir/taskgraph_data.db?mode=ro exists: True
09/17/2021 10:39:51  natcap.invest.hra  DEBUG    resilience_attributes: ['recruitment rate', 'natural mortality rate', 'connectivity rate', 'recovery time']
09/17/2021 10:39:51  natcap.invest.hra  DEBUG    stressor_attributes: {'Docks_Wharves_Marinas': ['frequency of disturbance', 'change in area rating', 'change in structure rating', 'temporal overlap rating', 'management effectiveness', 'intensity rating'], 'Finfish_Aquaculture_Comm': ['frequency of disturbance', 'change in area rating', 'change in structure rating', 'temporal overlap rating', 'management effectiveness', 'intensity rating'], 'Rec_Fishing': ['frequency of disturbance', 'change in area rating', 'change in structure rating', 'temporal overlap rating', 'management effectiveness', 'intensity rating'], 'Shellfish_Aquaculture_Comm': ['frequency of disturbance', 'change in area rating', 'change in structure rating', 'temporal overlap rating', 'management effectiveness', 'intensity rating']}
09/17/2021 10:39:51  natcap.invest.hra  INFO     Recovery dataframe was created successfully.
09/17/2021 10:39:51  natcap.invest.hra  DEBUG    multi_index: MultiIndex([(  'eelgrass',      'Docks_Wharves_Marinas'),
            (  'eelgrass',   'Finfish_Aquaculture_Comm'),
            (  'eelgrass',                'Rec_Fishing'),
            (  'eelgrass', 'Shellfish_Aquaculture_Comm'),
            ('hardbottom',      'Docks_Wharves_Marinas'),
            ('hardbottom',   'Finfish_Aquaculture_Comm'),
            ('hardbottom',                'Rec_Fishing'),
            ('hardbottom', 'Shellfish_Aquaculture_Comm'),
            (      'kelp',      'Docks_Wharves_Marinas'),
            (      'kelp',   'Finfish_Aquaculture_Comm'),
            (      'kelp',                'Rec_Fishing'),
            (      'kelp', 'Shellfish_Aquaculture_Comm'),
            ('softbottom',      'Docks_Wharves_Marinas'),
            ('softbottom',   'Finfish_Aquaculture_Comm'),
            ('softbottom',                'Rec_Fishing'),
            ('softbottom', 'Shellfish_Aquaculture_Comm')],
           names=['HABITAT', 'STRESSOR'])
09/17/2021 10:39:51  natcap.invest.utils INFO     Elapsed time: 0.35s
Traceback (most recent call last):
  File "C:\Users\dmf\projects\invest\env\Scripts\invest-script.py", line 33, in <module>
    sys.exit(load_entry_point('natcap.invest==3.9.0.post537+g8652471a', 'console_scripts', 'invest')())
  File "C:\Users\dmf\projects\invest\env\lib\site-packages\natcap.invest-3.9.0.post537+g8652471a-py3.8-win-amd64.egg\natcap\invest\cli.py", line 590, in main
    getattr(model_module, 'execute')(parsed_datastack.args)
  File "C:\Users\dmf\projects\invest\env\lib\site-packages\natcap.invest-3.9.0.post537+g8652471a-py3.8-win-amd64.egg\natcap\invest\hra.py", line 271, in execute
    overlap_df = _get_overlap_dataframe(
  File "C:\Users\dmf\projects\invest\env\lib\site-packages\natcap.invest-3.9.0.post537+g8652471a-py3.8-win-amd64.egg\natcap\invest\hra.py", line 2899, in _get_overlap_dataframe
    dq = row_data[idx + 1]
  File "c:\users\dmf\projects\invest\env\lib\site-packages\pandas\core\series.py", line 939, in __getitem__
    return self._values[key]
IndexError: index 13 is out of bounds for axis 0 with size 13
09/17/2021 10:39:51  taskgraph.Task     DEBUG    shutting down workers
09/17/2021 10:39:51  taskgraph.Task     DEBUG    taskgraph terminated
```

But in the workspace's logfile we're missing the Traceback. The last thing we get is:
```
09/17/2021 10:39:51  natcap.invest.utils INFO     Elapsed time: 0.35s
```
It's curious that the Traceback comes *after* this INFO message on the console streams. 

Testing another model (Carbon) that ends in error, the Traceback again comes after the INFO message on the console streams. But in the logfile, the Traceback is logged *before* the final `INFO Elapsed time` message. 

Is there some race condition at play with the logfile where sometimes it's closed too soon?

**Comment by davemfish** [comment]
Perhaps related to this issue: It seems like sometimes (most of the time?) the python Traceback from invest is emitted through stdout and stderr. In those cases, it also appears in the logfile as expected.

In this HRA case, the Traceback also does not come through `stdout`, only `stderr`.

**Comment by phargogh** [comment]
Hey @davemfish I think there are a couple of interrelated issues here that mostly come down to some ideas around logging that seemed like good ideas at the time but were really incomplete and then I do think there's a good ol' race condition.

The main issue here is that there were inconsistent handling of logfiles across our various ways of running InVEST.  The CLI had logging handlers to the logfile and stdout, but didn't `LOGGER.exception` when it found an uncaught error.  The Qt UI had an additional handler in the model logging progress dialog, but the important detail is that it had its own `LOGGER.exception` when the model errored.  These have been unified in the terribly-named `utils.prepare_workspace` now so that as long as we use that context manager, logging to the logfile will be consistent.

There's a related issue of exceptions not being printed to stdout (or the logfile) by default.  This has been corrected: the default log level is now `logging.ERROR`, which will allow exceptions to be logged to all handlers.

The race condition has to do with the exception when it is raised.  I can only speculate (and badly) about why this is happening specifically for HRA, but I think the main issue here has to do with a race condition between a raised exception and the logging that will log it.  I believe that the logging fix I mentioned will ensure that the logfile and any attached handlers will log the exception, but it is not clear to me if we have a guarantee that this will happen before the program terminates.  In any case, an exception from a model run when `--headless` should for sure go to stderr.
