### ISSUE TITLE
Restrict the PATH available to PyInstaller?

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#665]
With the InVEST 3.9.1 release, we had an interesting issue where a malformed PATH caused InVEST to fail with the following exception:

```python
Jesse Goldstein@NATCAP-JGLSTN C:\Users\Jesse Goldstein
$ "C:\Program Files\InVEST_3.9.1_x64\invest-3-x64\invest.exe
Traceback (most recent call last):
  File "natcap\invest\cli.py", line 19, in <module>
ImportError: attempted relative import with no known parent package

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "natcap\invest\cli.py", line 24, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "natcap\invest\__init__.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "pygeoprocessing\__init__.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "pygeoprocessing\geoprocessing.py", line 16, in <module>
  File "src\pygeoprocessing\geoprocessing_core.pyx", line 26, in init pygeoprocessing.geoprocessing_core
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "osgeo\__init__.py", line 11, in <module>
  File "os.py", line 1109, in add_dll_directory
OSError: [WinError 87] The parameter is incorrect: '"C:\\Users\\Jesse Goldstein\\anaconda3'
[14436] Failed to execute script 'cli' due to unhandled exception!
```

We're pretty sure that the ultimate issue was in this portion of the `PATH`, which _is_ malformed (note the double-quotes):

```text
C:\ProgramData\DockerDesktop\version-bin;
"C:\Users\Jesse Goldstein\anaconda3;
C:\Users\Jesse Goldstein\anaconda3\Scripts";
C:\Users\Jesse Goldstein\AppData\Local\Programs\Python\Python37-32\Scripts\;
```

This is then ultimately causing the issue because `os.add_dll_directory('"C:\Users\Jesse Goldstein\anaconda3')` raises the `WinError 87` noted in the original exception, and _this_ is happening because of a [recent change in GDAL's `__init__.py`](https://github.com/OSGeo/gdal/pull/3923/files#diff-6319ee1887f8072a84f89d0b243ac76dfefa5497ed424b098c7e98640b97b0c5) where every directory on the PATH is being added as a DLL directory.

In theory, we should be able to control what PyInstaller sees as the `PATH` and if we're able to, it'd be really great to be able to have InVEST be a self-contained application.  Do we need InVEST to access the system `PATH` to import some system libraries or redistributables?  It's worth looking into in order to prevent accessing the user's `PATH` at all.

**Comment by davemfish** [comment]
This is a bit of a tangent, but, I just encountered this myself running the latest invest binaries in the workbench. 

The binaries are executed like this, overwriting the `PATH` in the process (I don't recall why we're doing it that way). 

```javascript
  const pythonServerProcess = spawn(
    path.basename(investExe),
    investExe,
    ['serve', '--port', process.env.PORT],
    {
      env: {
        PATH: path.dirname(investExe),
      },
    }
  );
```

But windows raised the same [WinError 87] on `path.dirname(investExe)`. It's not obvious what's wrong with that path, but we can easily work around this in the workbench by not setting `env.PATH` here.

Anyway, I mention it here because setting `env.PATH` at `spawn` is theoretically a way to prevent the exe from accessing to the rest of the user's `PATH`, if it worked.

**Comment by davemfish** [comment]
This has come up a third time now: https://community.naturalcapitalproject.org/t/carbon-values-error/2203/10

Jesse's example did seem to have a bad path in the `PATH`, with the unclosed quotation. But the other two have seemingly valid `PATH`s. Given that, and the fact that this release is fairly new, this bug probably affects a lot of people so I wonder if we should elevate this to critical and try to patch ASAP. It's not obvious what the solution is, but asking users to edit their otherwise valid `PATH` doesn't feel great.

**Comment by dcdenu4** [comment]
That user issue is pretty strange. I agree that having the user edit their PATH does not feel great. My only concern would be that  this approach would hide some development things or cover up things we are doing wrong? I'm not sure if this a warranted concern.

The only helpful thing I could find on this users issue was related to this post: https://serverfault.com/questions/300544/environment-variables-in-path-not-expanded-for-non-admin-command-prompt. I thought, I hope the local vs admin install option isn't the culprit here.

**Comment by davemfish** [comment]
> That user issue is pretty strange. 

I'm no Windows `PATH` expert, but the forum person's path looked okay to me.

**Comment by davemfish** [comment]
I have new examples of this same or similar problem. I recently built binaries from my local conda env and they yield this:

```
...
File "osgeo\__init__.py", line 10, in <module>
  File "os.py", line 1109, in add_dll_directory
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\dmf\\projects\\invest\\env\\Library\\usr\\bin'
```
Indeed that path does not exist, but I would think it should be okay to have an entry in `PATH` that does not exist. At least in the context of how I think about the purpose of `PATH`: locations that should be scanned for the name of an exe, but if something isn't found, just move on to the next one.

Here's the same example, but now the same binaries are being executed by node in the Workbench, where my `PATH` now includes another non-existent directory:

```
...
File "osgeo\__init__.py", line 10, in <module>
  File "os.py", line 1109, in add_dll_directory
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\dmf\\AppData\\Local\\Yarn\\Data\\link\\node_modules\\.bin'
```

**Comment by dcdenu4** [comment]
>>That user issue is pretty strange.

>I'm no Windows PATH expert, but the forum person's path looked okay to me.

Yea, I was referring to the idea of the %USERPROFILE% env not expanding, I thought that was a funky idea.

**Comment by phargogh** [comment]
Yep, this is for sure a bug, though the solution is not yet clear.  This is a good thing to add to 3.9.2, and I just added the critical label as well since there do seem to be a lot of people affected.
