### ISSUE TITLE
AWY does not support GPKG watersheds

### ISSUE THREAD

**Issue by davemfish** [natcap/invest#758]
Here's an example traceback when using a GPKG watersheds input (or subwatersheds).

```
2021-12-03 11:22:34,063 (natcap.invest.utils) utils.prepare_workspace(163) ERROR Exception while executing Annual-Water-Yield
Traceback (most recent call last):
  File "c:\program files\python38\lib\site-packages\natcap\invest\utils.py", line 161, in prepare_workspace
    yield
  File "c:\program files\python38\lib\site-packages\natcap\invest\ui\model.py", line 1650, in _logged_target
    return self.target(args=args)
  File "c:\program files\python38\lib\site-packages\natcap\invest\annual_water_yield.py", line 597, in execute
    create_output_vector_task = graph.add_task(
  File "c:\program files\python38\lib\site-packages\taskgraph\Task.py", line 674, in add_task
    new_task._call()
  File "c:\program files\python38\lib\site-packages\taskgraph\Task.py", line 1093, in _call
    payload = self._func(*self._args, **self._kwargs)
  File "c:\program files\python38\lib\site-packages\natcap\invest\annual_water_yield.py", line 675, in create_vector_output
    _add_zonal_stats_dict_to_shape(
  File "c:\program files\python38\lib\site-packages\natcap\invest\annual_water_yield.py", line 1096, in _add_zonal_stats_dict_to_shape
    if stats_map[feature_fid]['count'] > 0:
KeyError: 0
```

The problem is the mismatch of FIDs between gpkg (start at 1) and shapefiles (start at 0) and the fact that the model always creates an output shapefile and iterates over it's FIDs to find the stats associated with each watershed.

**Comment by davemfish** [comment]
We're using FIDs for similar purposes in the following models, so we should look more closely at these:

- [ ] AWY
- [ ] forest carbon edge effects
- [ ] globio
- [ ] NDR
- [ ] Pollination
- [ ] Recreation
- [ ] SDR
- [ ] Stormwater
- [ ] Urban Cooling
- [ ] Urban Flood
- [ ] Wind Energy
- [ ] `utils._assert_vectors_equal` -- do we really want to assert FIDs are equal?

Other models not listed use FIDs for good reasons such as:
- logging like `LOGGER.warning("Feature {FID} of {vector_path} has some problem...")`
- as the index for an Rtree used only to index into the same layer
