### ISSUE TITLE
Coax InVEST to run on ARM Windows?

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#790]
In testing InVEST for the 310 release, I came across a couple errors that did not immediately sound like they were architecture-related:

## Error 1: A dynamic link library (DLL) initialization routine failed.
```
C:\Program Files\InVEST_3.9.2.post827+g053f21ce5_x64\invest-3-x64>invest.exe run carbon
Traceback (most recent call last):
  File "osgeo\__init__.py", line 29, in swig_import_helper
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 657, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 556, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1166, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed while importing _gdal: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "natcap\invest\cli.py", line 18, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "natcap\invest\datastack.py", line 33, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "osgeo\__init__.py", line 45, in <module>
  File "osgeo\__init__.py", line 41, in swig_import_helper
ImportError: Traceback (most recent call last):
  File "osgeo\__init__.py", line 29, in swig_import_helper
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 657, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 556, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1166, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed while importing _gdal: A dynamic link library (DLL) initialization routine failed.

On Windows, with Python >= 3.8, DLLs are no longer imported from the PATH.
If gdalXXX.dll is in the PATH, then set the USE_PATH_FOR_GDAL_PYTHON=YES environment variable
to feed the PATH into os.add_dll_directory().
[2672] Failed to execute script 'cli' due to unhandled exception!

C:\Program Files\InVEST_3.9.2.post827+g053f21ce5_x64\invest-3-x64>
```

This error also showed up in the Event Viewer as 2 separate "Application Error" events that both have the same timestamp (at least within the same second):

* Event ID 1000: [event-id-1000.txt](https://github.com/natcap/invest/files/7738221/event-id-1000.txt)
* Event ID 1005: [event-id-1005.txt](https://github.com/natcap/invest/files/7738223/event-id-1005.txt)

Although it showed up in Event Viewer as 2 separate events, they both have something to do with `tiledb.dll` and are clearly from the same report (they have the same report ID).

## Error 2: The specified procedure could not be found.

Then, later, after I installed the [latest MSVC Redistributable](https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022), I got a slightly different error:

```
C:\Program Files\InVEST_3.9.2.post827+g053f21ce5_x64\invest-3-x64>.\invest --list
Traceback (most recent call last):
  File "osgeo\__init__.py", line 29, in swig_import_helper
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 657, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 556, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1166, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed while importing _gdal: The specified procedure could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "natcap\invest\cli.py", line 18, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "natcap\invest\datastack.py", line 33, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "osgeo\__init__.py", line 45, in <module>
  File "osgeo\__init__.py", line 41, in swig_import_helper
ImportError: Traceback (most recent call last):
  File "osgeo\__init__.py", line 29, in swig_import_helper
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 657, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 556, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1166, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed while importing _gdal: The specified procedure could not be found.

On Windows, with Python >= 3.8, DLLs are no longer imported from the PATH.
If gdalXXX.dll is in the PATH, then set the USE_PATH_FOR_GDAL_PYTHON=YES environment variable
to feed the PATH into os.add_dll_directory().
[956] Failed to execute script 'cli' due to unhandled exception!

C:\Program Files\InVEST_3.9.2.post827+g053f21ce5_x64\invest-3-x64>
```

This error did _not_ show up in the event viewer at all.

These issues were reproduced on my ARM Mac in windows 11 (ARM) and also windows 10 (ARM) via windows VMs in parallels.  @dcdenu4 and @davemfish are not experiencing these issues on their windows systems.

Windows is supposed to have an x86 translation layer, so I'm hoping there are just a few hoops we need to jump through and document for future us.

UPDATE: Running this on GCP in an x64 Windows Server 2019 VM works great, exactly as expected, no issues at all.

**Comment by phargogh** [comment]
Working on this in `critical/3.10-release-fails-on-win11`

**Comment by phargogh** [comment]
OK, so a user reported this on the forums as well: https://community.naturalcapitalproject.org/t/invest-3-10-1-x64-installation-problems/2465/7

This user has an Intel Celeron processor, so this isn't exclusive to ARM.  Maybe there's some feature missing from Celeron?

**Comment by phargogh** [comment]
I'm not sure about the Celeron issue I mentioned on Feb 1, but I just tested the Workbench on my ARM windows 11 install and the workbench runs well!  There are some issues with the taskgraph database being locked, but that's probably not an InVEST issue as much as it is likely to be some other program that parallels is managing.  So just a heads up that if we have folks using Paralells Desktop, we can just say "Use the Workbench" to resolve this issue.

**Comment by phargogh** [comment]
This has not been an issue of late and we are moving to the workbench anyways.  WontFix.
