### ISSUE TITLE
HRA tests failing in actions

### ISSUE THREAD

**Issue by dcdenu4** [natcap/invest#835]
I'm seeing some HRA tests fail in an auto PR for merging `main` into `release/3.10.2. These tests must not have been failing when merging into `main`.  They are failing for Windows and Mac Python 3.8, 3.9. Python 3.7 tests pass okay. https://github.com/natcap/invest/pull/832

This line in HRAs `_zonal_stats_to_csv` function appears to be the culprit:
`    stats_df = pandas.DataFrame(index=overlap_df.index, columns=columns)`

```
2022-01-25T19:17:25.4015294Z =========================== short test summary info ===========================
2022-01-25T19:17:25.4015663Z FAILED tests/test_hra.py::HraRegressionTests::test_hra_no_subregion_multiplicative_exponential
2022-01-25T19:17:25.4016097Z FAILED tests/test_hra.py::HraRegressionTests::test_hra_regression_euclidean_linear
2022-01-25T19:17:25.4016474Z ====== 2 failed, 585 passed, 8 skipped, 15 warnings in 457.84s (0:07:37) ======
```

```
2022-01-25T19:12:49.9538188Z tests/test_hra.py::HraRegressionTests::test_aoi_no_projection PASSED
2022-01-25T19:12:56.0746787Z tests/test_hra.py::HraRegressionTests::test_hra_no_subregion_multiplicative_exponential 01/25/2022 19:12:56  taskgraph.Task     ERROR    Something went wrong when adding task zonal_stats_to_csv (55), terminating taskgraph.
2022-01-25T19:12:56.0747696Z Traceback (most recent call last):
2022-01-25T19:12:56.0748148Z   File "C:\Miniconda\envs\windows-latest-test-env\lib\site-packages\taskgraph\Task.py", line 674, in add_task
2022-01-25T19:12:56.0752229Z     new_task._call()
2022-01-25T19:12:56.0752790Z   File "C:\Miniconda\envs\windows-latest-test-env\lib\site-packages\taskgraph\Task.py", line 1093, in _call
2022-01-25T19:12:56.0753434Z     payload = self._func(*self._args, **self._kwargs)
2022-01-25T19:12:56.0754009Z   File "C:\Miniconda\envs\windows-latest-test-env\lib\site-packages\natcap\invest\hra.py", line 1186, in _zonal_stats_to_csv
2022-01-25T19:12:56.0754603Z     stats_df = pandas.DataFrame(index=overlap_df.index, columns=columns)
2022-01-25T19:12:56.0755163Z   File "C:\Miniconda\envs\windows-latest-test-env\lib\site-packages\pandas\core\frame.py", line 637, in __init__
2022-01-25T19:12:56.0755760Z     mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
2022-01-25T19:12:56.0756750Z   File "C:\Miniconda\envs\windows-latest-test-env\lib\site-packages\pandas\core\internals\construction.py", line 502, in dict_to_mgr
2022-01-25T19:12:56.0758177Z     return arrays_to_mgr(arrays, columns, index, dtype=dtype, typ=typ, consolidate=copy)
2022-01-25T19:12:56.0758923Z   File "C:\Miniconda\envs\windows-latest-test-env\lib\site-packages\pandas\core\internals\construction.py", line 150, in arrays_to_mgr
2022-01-25T19:12:56.0759763Z     raise ValueError("len(arrays) must match len(columns)")
2022-01-25T19:12:56.0760244Z ValueError: len(arrays) must match len(columns)
```

**Comment by dcdenu4** [comment]
It looks like `pandas` was updated to 1.4.0. This is consistent with the error that is being produced and would explain why we didn't see this error in the initial PR into `main`.

```
< pandas=1.4.0=py38h5d928e2_0
---
> pandas=1.3.5=py38h5d928e2_0
```

**Comment by dcdenu4** [comment]
Accidentally closed.

**Comment by dcdenu4** [comment]
It looks like with pandas 1.4.0 passing a `map` iterable for _columns_ in `pandas.DataFrame(index=index, columns=columns)` now returns a `ValueError`.

In 1.3.4 passing a `map` iterable for _columns_ would produce:
```python
>>> stats_df = pandas.DataFrame(index=index, columns=columns)
>>> stats_df
Empty DataFrame
Columns: []
Index: [(habitat_0, stressor_0), (habitat_0, stressor_1), (habitat_1, stressor_0), (habitat_1, stressor_1)]
```

The latter does not seem right either as it's missing the columns. It's possible this has been a silent bug and is now handled properly in pandas.

If you pass in a list for the columns as opposed to the iterable, you get:
```python
>>> stats_df = pandas.DataFrame(index=index, columns=columns_list)
>>> stats_df
                     E_MEAN E_MIN E_MAX C_MEAN C_MIN C_MAX R_MEAN R_MIN R_MAX R_%HIGH R_%MED R_%LOW
HABITAT   STRESSOR
habitat_0 stressor_0    NaN   NaN   NaN    NaN   NaN   NaN    NaN   NaN   NaN     NaN    NaN    NaN
          stressor_1    NaN   NaN   NaN    NaN   NaN   NaN    NaN   NaN   NaN     NaN    NaN    NaN
habitat_1 stressor_0    NaN   NaN   NaN    NaN   NaN   NaN    NaN   NaN   NaN     NaN    NaN    NaN
          stressor_1    NaN   NaN   NaN    NaN   NaN   NaN    NaN   NaN   NaN     NaN    NaN    NaN
```
This is what I would think is desired, but I'm just looking at this HRA code for the first time.

**Comment by dcdenu4** [comment]
If this has been a silent bug all along I don't think it makes sense to pin the pandas version so these tests pass.

**Comment by dcdenu4** [comment]
This is the multi-index and what `map` yields for columns
```
MultiIndex([('habitat_0', 'stressor_0'),
            ('habitat_0', 'stressor_1'),
            ('habitat_1', 'stressor_0'),
            ('habitat_1', 'stressor_1')],
           names=['HABITAT', 'STRESSOR'])
E_MEAN
E_MIN
E_MAX
C_MEAN
C_MIN
C_MAX
R_MEAN
R_MIN
R_MAX
R_%HIGH
R_%MEDIUM
R_%LOW
```
This is the pandas 1.4.0 output for the created dataframe from the mulit-index and columns as a list from an HRA test
```
______________________________________________________________________ HraRegressionTests.test_hra_regression_euclidean_linear ______________________________________________________________________ --------------------------------------------------------------------------------------- Captured stdout call ----------------------------------------------------------------------------------------
                     E_MEAN E_MIN E_MAX C_MEAN C_MIN C_MAX R_MEAN R_MIN R_MAX R_%HIGH R_%MEDIUM R_%LOW
HABITAT   STRESSOR
habitat_0 stressor_0    NaN   NaN   NaN    NaN   NaN   NaN    NaN   NaN   NaN     NaN       NaN    NaN
          stressor_1    NaN   NaN   NaN    NaN   NaN   NaN    NaN   NaN   NaN     NaN       NaN    NaN
habitat_1 stressor_0    NaN   NaN   NaN    NaN   NaN   NaN    NaN   NaN   NaN     NaN       NaN    NaN
          stressor_1    NaN   NaN   NaN    NaN   NaN   NaN    NaN   NaN   NaN     NaN       NaN    NaN
```
This is the pandas 1.4.0 output for the finished dataframe from the `_zonal_stats` function from an HRA test
```
                               SUBREGION E_MEAN E_MIN E_MAX    C_MEAN     C_MIN     C_MAX    R_MEAN     R_MIN     R_MAX R_%HIGH R_%MEDIUM R_%LOW
HABITAT   STRESSOR
habitat_0 stressor_0            region A    1.0   1.0   1.0      2.25       2.0       2.5  1.325825   1.06066   1.59099     0.0     100.0    0.0
          stressor_1            region A    2.1   0.0   3.0       2.2       0.0       3.0  1.922198       0.0       3.0    50.0      20.0   30.0
habitat_1 stressor_0            region A    0.0   0.0   0.0  1.666667  1.666667  1.666667       0.0       0.0       0.0     0.0       0.0  100.0
          stressor_1            region A    3.0   3.0   3.0  2.333333  2.333333  2.333333   2.54951   2.54951   2.54951   100.0       0.0    0.0
habitat_0 (FROM ALL STRESSORS)  region A   1.55   0.5   2.0       2.2  1.333333  2.666667  1.624012   0.53033  2.295495    50.0      20.0   30.0
habitat_1 (FROM ALL STRESSORS)  region A    1.5   1.5   1.5       2.0       2.0       2.0  1.274755  1.274755  1.274755     0.0     100.0    0.0
habitat_0 stressor_0            region B    1.0   1.0   1.0      2.25       2.0       2.5  1.325825   1.06066   1.59099     0.0     100.0    0.0
          stressor_1            region B    2.1   0.0   3.0       2.2       0.0       3.0  1.922198       0.0       3.0    50.0      20.0   30.0
habitat_1 stressor_0            region B    0.0   0.0   0.0  2.333333  2.333333  2.333333       0.0       0.0       0.0     0.0       0.0  100.0
          stressor_1            region B    3.0   3.0   3.0  2.333333  2.333333  2.333333   2.54951   2.54951   2.54951   100.0       0.0    0.0
habitat_0 (FROM ALL STRESSORS)  region B   1.55   0.5   2.0       2.2  1.333333  2.666667  1.624012   0.53033  2.295495    50.0      20.0   30.0
habitat_1 (FROM ALL STRESSORS)  region B    1.5   1.5   1.5       2.5       2.5       2.5  1.274755  1.274755  1.274755     0.0     100.0    0.0
habitat_0 stressor_0            region C   None  None  None      None      None      None      None      None      None    None      None   None
          stressor_1            region C   None  None  None      None      None      None      None      None      None    None      None   None
habitat_1 stressor_0            region C   None  None  None      None      None      None      None      None      None    None      None   None
          stressor_1            region C   None  None  None      None      None      None      None      None      None    None      None   None
habitat_0 (FROM ALL STRESSORS)  region C   None  None  None      None      None      None      None      None      None    None      None   None
habitat_1 (FROM ALL STRESSORS)  region C   None  None  None      None      None      None      None      None      None    None      None   None
```
This is the pandas 1.3.4 output for the created dataframe from the mulit-index and columns as a map iterable from an HRA test
```
______________________________________________________________________ HraRegressionTests.test_hra_regression_euclidean_linear ______________________________________________________________________ --------------------------------------------------------------------------------------- Captured stdout call ---------------------------------------------------------------------------------------- Empty DataFrame
Columns: []
Index: [(habitat_0, stressor_0), (habitat_0, stressor_1), (habitat_1, stressor_0), (habitat_1, stressor_1)]
```
This is the pandas 1.3.4 output for the finished dataframe from the `_zonal_stats` function from an HRA test
```
                               SUBREGION  E_MEAN  E_MIN  E_MAX    C_MEAN     C_MIN     C_MAX    R_MEAN     R_MIN     R_MAX  R_%HIGH  R_%MEDIUM  R_%LOW
HABITAT   STRESSOR
habitat_0 stressor_0            region A    1.00    1.0    1.0  2.250000  2.000000  2.500000  1.325825  1.060660  1.590990      0.0      100.0     0.0
          stressor_1            region A    2.10    0.0    3.0  2.200000  0.000000  3.000000  1.922198  0.000000  3.000000     50.0       20.0    30.0
habitat_1 stressor_0            region A    0.00    0.0    0.0  1.666667  1.666667  1.666667  0.000000  0.000000  0.000000      0.0        0.0   100.0
          stressor_1            region A    3.00    3.0    3.0  2.333333  2.333333  2.333333  2.549510  2.549510  2.549510    100.0        0.0     0.0
habitat_0 (FROM ALL STRESSORS)  region A    1.55    0.5    2.0  2.200000  1.333333  2.666667  1.624012  0.530330  2.295495     50.0       20.0    30.0
habitat_1 (FROM ALL STRESSORS)  region A    1.50    1.5    1.5  2.000000  2.000000  2.000000  1.274755  1.274755  1.274755      0.0      100.0     0.0
habitat_0 stressor_0            region B    1.00    1.0    1.0  2.250000  2.000000  2.500000  1.325825  1.060660  1.590990      0.0      100.0     0.0
          stressor_1            region B    2.10    0.0    3.0  2.200000  0.000000  3.000000  1.922198  0.000000  3.000000     50.0       20.0    30.0
habitat_1 stressor_0            region B    0.00    0.0    0.0  2.333333  2.333333  2.333333  0.000000  0.000000  0.000000      0.0        0.0   100.0
          stressor_1            region B    3.00    3.0    3.0  2.333333  2.333333  2.333333  2.549510  2.549510  2.549510    100.0        0.0     0.0
habitat_0 (FROM ALL STRESSORS)  region B    1.55    0.5    2.0  2.200000  1.333333  2.666667  1.624012  0.530330  2.295495     50.0       20.0    30.0
habitat_1 (FROM ALL STRESSORS)  region B    1.50    1.5    1.5  2.500000  2.500000  2.500000  1.274755  1.274755  1.274755      0.0      100.0     0.0
habitat_0 stressor_0            region C     NaN    NaN    NaN       NaN       NaN       NaN       NaN       NaN       NaN      NaN        NaN     NaN
          stressor_1            region C     NaN    NaN    NaN       NaN       NaN       NaN       NaN       NaN       NaN      NaN        NaN     NaN
habitat_1 stressor_0            region C     NaN    NaN    NaN       NaN       NaN       NaN       NaN       NaN       NaN      NaN        NaN     NaN
          stressor_1            region C     NaN    NaN    NaN       NaN       NaN       NaN       NaN       NaN       NaN      NaN        NaN     NaN
habitat_0 (FROM ALL STRESSORS)  region C     NaN    NaN    NaN       NaN       NaN       NaN       NaN       NaN       NaN      NaN        NaN     NaN
habitat_1 (FROM ALL STRESSORS)  region C     NaN    NaN    NaN       NaN       NaN       NaN       NaN       NaN       NaN      NaN        NaN     NaN
```
