### ISSUE TITLE
readthedocs failing recently on PRs

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#933]
Recent PRs have had failing RTD builds with the following exception:

```python
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/invest/conda/932/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/docs/checkouts/readthedocs.org/user_builds/invest/conda/932/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/invest/conda/932/lib/python3.9/site-packages/sphinx/__main__.py", line 13, in <module>
    from sphinx.cmd.build import main
  File "/home/docs/checkouts/readthedocs.org/user_builds/invest/conda/932/lib/python3.9/site-packages/sphinx/cmd/build.py", line 25, in <module>
    from sphinx.application import Sphinx
  File "/home/docs/checkouts/readthedocs.org/user_builds/invest/conda/932/lib/python3.9/site-packages/sphinx/application.py", line 43, in <module>
    from sphinx.registry import SphinxComponentRegistry
  File "/home/docs/checkouts/readthedocs.org/user_builds/invest/conda/932/lib/python3.9/site-packages/sphinx/registry.py", line 24, in <module>
    from sphinx.builders import Builder
  File "/home/docs/checkouts/readthedocs.org/user_builds/invest/conda/932/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 26, in <module>
    from sphinx.util import import_object, logging, rst, progress_message, status_iterator
  File "/home/docs/checkouts/readthedocs.org/user_builds/invest/conda/932/lib/python3.9/site-packages/sphinx/util/rst.py", line 22, in <module>
    from jinja2 import environmentfilter
ImportError: cannot import name 'environmentfilter' from 'jinja2' (/home/docs/checkouts/readthedocs.org/user_builds/invest/conda/932/lib/python3.9/site-packages/jinja2/__init__.py)
```

**Comment by phargogh** [comment]
Now it's failing on `flask-cors`.
