### ISSUE TITLE
Model run tests failing under "build and install wheel"

### ISSUE THREAD

**Issue by dcdenu4** [natcap/invest#937]
Seeing in this in multiple PRs, not sure if it's been documented yet.

Seemingly happening during : ` python -m twine check dist/*`

https://github.com/natcap/invest/runs/5891391760?check_suite_focus=true

```
 removing build\bdist.win-amd64\wheel
C:\Users\runneradmin\AppData\Local\Temp\build-env-7ascavj7\lib\site-packages\wheel\bdist_wheel.py:82: RuntimeWarning: Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
  warn=(impl == 'cp')):
C:\Users\runneradmin\AppData\Local\Temp\build-env-7ascavj7\lib\site-packages\wheel\bdist_wheel.py:87: RuntimeWarning: Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
  sys.version_info < (3, 8))) \
Successfully built natcap.invest-3.10.2.post2283+ge3cee0210-cp37-cp37m-win_amd64.whl
Checking 
Traceback (most recent call last):
  File "C:\Miniconda\envs\test\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Miniconda\envs\test\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Miniconda\envs\test\lib\site-packages\twine\__main__.py", line 51, in <module>
    sys.exit(main())
  File "C:\Miniconda\envs\test\lib\site-packages\twine\__main__.py", line 33, in main
    error = cli.dispatch(sys.argv[1:])
  File "C:\Miniconda\envs\test\lib\site-packages\twine\cli.py", line 124, in dispatch
    return main(args.args)
  File "C:\Miniconda\envs\test\lib\site-packages\twine\commands\check.py", line 183, in main
    return check(parsed_args.dists, strict=parsed_args.strict)
  File "C:\Miniconda\envs\test\lib\site-packages\twine\commands\check.py", line 129, in check
    warnings, is_ok = _check_file(filename, render_warning_stream)
  File "C:\Miniconda\envs\test\lib\site-packages\twine\commands\check.py", line 92, in _check_file
    description, stream=render_warning_stream, **params
  File "C:\Miniconda\envs\test\lib\site-packages\readme_renderer\rst.py", line 114, in render
    return clean(rendered)
  File "C:\Miniconda\envs\test\lib\site-packages\readme_renderer\clean.py", line 86, in clean
    parse_email=False,
TypeError: __init__() got an unexpected keyword argument 'styles'
dist/natcap.invest-3.10.2.post2283+ge3cee0210-cp37-cp37m-win_amd64.whl: 
Error: Process completed with exit code 1.
```

**Comment by dcdenu4** [comment]
Duplicate of #936
