### ISSUE TITLE
Crop Production: unsupported operand type(s) for &: 'slice' and 'bool'

### ISSUE THREAD

**Issue by emlys** [natcap/invest#949]
A bug in Crop Production handling of nodata that only arises when nodata is `None`. Triggered by [this user](https://community.naturalcapitalproject.org/t/crop-production-appears-to-be-an-issue-with-the-input-data/2640/4) using a different version of the Monfreda data set due to #931. `slice(None)` cannot be used in place of a numpy array. Should check the rest of the models for this error too.

Error:
```
2022-04-14 16:19:06,070 (natcap.invest.utils) utils.prepare_workspace(167) ERROR Exception while executing Crop-Production-Percentile
Traceback (most recent call last):
  File "natcap\invest\utils.py", line 165, in prepare_workspace
  File "natcap\invest\ui\model.py", line 1649, in _logged_target
  File "natcap\invest\crop_production_percentile.py", line 563, in execute
  File "taskgraph\Task.py", line 674, in add_task
  File "taskgraph\Task.py", line 1093, in _call
  File "natcap\invest\crop_production_percentile.py", line 776, in tabulate_results
TypeError: unsupported operand type(s) for &: 'slice' and 'bool'
```
Problematic code:
```
valid_mask = slice(None)
if observed_yield_nodata is not None:
    valid_mask = ~utils.array_equals_nodata(
        yield_block, observed_yield_nodata)
production_pixel_count += numpy.count_nonzero(
    valid_mask & (yield_block > 0))
```

**Comment by phargogh** [comment]
Oh this is really interesting!  No, it should not be used as a numpy array, but there are cases where it could make sense to use `slice(None)` instead of `numpy.ones`.

This sort of thing (presence/absence of nodatas) would be great to include in https://github.com/natcap/invest/issues/536 if/when we get to it.
