### ISSUE TITLE
CV bathymetry masking does not handle unset nodata

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#992]
A [user on the forums](https://community.naturalcapitalproject.org/t/coastal-vulnerability-model-not-running-due-to-nonetype-error/2813) is reporting an error that's occurring because the nodata value is not defined (and we can't set a numpy array value to be `None`).

Here's the minimum reproducible issue:

```python
import numpy
a = numpy.array((4, 4), dtype=numpy.int32)
a[:] = None
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by davemfish** [comment]
It seems like we didn't get a complete fix for this. Rob shared a dataset with me that has a `None` nodata value and when we try using the max value allowed by the raster's datatype (our original fix to this issue), we raise this:

```
Traceback (most recent call last):
  File "natcap\invest\utils.py", line 164, in prepare_workspace
  File "invest\cli.py", line 469, in main
  File "natcap\invest\coastal_vulnerability.py", line 843, in execute
  File "taskgraph\Task.py", line 674, in add_task
  File "taskgraph\Task.py", line 1093, in _call
  File "natcap\invest\coastal_vulnerability.py", line 2216, in warp_and_mask_bathymetry
  File "pygeoprocessing\geoprocessing.py", line 426, in raster_calculator
  File "osgeo\gdal.py", line 3847, in SetNoDataValue
TypeError: in method 'Band_SetNoDataValue', argument 2 of type 'double'
```

**Comment by phargogh** [comment]
Fun!  Based on the code, looks like we forgot to cast the nodata value to `float` before passing it to GDAL.  For some reason, numpy float32/float64 objects aren't considered valid `double`s to GDAL.  I think I missed this before because I was testing the op and not `warp_and_mask_bathymetry`.

**Comment by davemfish** [comment]
>looks like we forgot to cast the nodata value to float before passing it to GDAL. For some reason, numpy float32/float64 objects aren't considered valid doubles to GDAL.

Oh thanks for pointing that out! I'll submit a PR
